- icaruscode/TPC/ICARUSWireCell/icarus/nf.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-decode-to-sig.jsonnet
Here is the test command.
```
lar -n1 -c prodsingle_common_icarus.fcl -o gen.root
lar -n1 -c cosmics_g4_icarus_volCryostat.fcl gen.root -o g4.root
lar -n1 -c wcls-multitpc-sim-drift-simchannel.fcl g4.root -o wcsim.root
lar -n1 -c wcls-decode-to-sig.fcl wcsim.root -o decon.root
```
The output deconvolution result is in the unit of electrons but scaled by 0.1. One can change the scaling here: `icaruscode/TPC/ICARUSWireCell/icarus/wcls-decode-to-sig.jsonnet` 
```
frame_scale: [0.1, 0.1],
```
> fix a configuration bug for wirecell signal processing

- fcl/evd/overburden/CMakeLists.txt
- fcl/evd/overburden/evd_nooverburden_icarus.fcl
- fcl/evd/overburden/evd_overburden_icarus.fcl
- fcl/g4/overburden/cosmics_nooverburden_g4_icarus_volCryostat.fcl
- fcl/g4/overburden/cosmics_nooverburden_g4_icarus_volDetEnc.fcl
- fcl/g4/overburden/cosmics_overburden_g4_icarus_volCryostat.fcl
- fcl/g4/overburden/cosmics_overburden_g4_icarus_volDetEnc.fcl
- fcl/g4/overburden/nooverburden_g4_icarus.fcl
- fcl/g4/overburden/overburden_g4_icarus.fcl
- fcl/services/photpropservices_icarus.fcl
- fcl/services/services_icarus_simulation.fcl
`icaruscode` contains some overburden/no overburden configurations, which are currently using single first induction wires and therefore require a special PMT mapping. Their `PhotonVisibilityService` configuration has been updated to reflect that.
> Fixed G4 and event display configurations using single wire and photon visibility.

- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
Hi @SFBayLaser, this PR is for loading the new wire geometry for wirecell. The new wire geometry is converted from your feature branch "usher_finalsplitwiregeometry". 
Please merge this PR after you merge the fixed split geometry from your feature branch.
Also, could you help update a data file in `icarus_data`?  Just simply replace `icarus_data/WirecellData/icarus-wires-dualanode-v2.json.bz2` with `/icarus/app/users/wgu/larsoft/j07/wire-cell-data/icarus-wires-dualanode-v3.json.bz2`.
> update wirecell wire geometry with the fixed split layout

- icaruscode/Geometry/GeoObjectSorterICARUS.cxx
- icaruscode/Geometry/GeoObjectSorterPMTasTPC.cxx
- icaruscode/Geometry/GeoObjectSorterPMTasTPC.h
- icaruscode/Geometry/details/AuxDetSorting.cxx
- icaruscode/Geometry/details/AuxDetSorting.h
- icaruscode/Geometry/details/PMTsorting.cxx
- icaruscode/Geometry/details/PMTsorting.h
The adoption of the split wire geometry channel mapping has caused the auxiliary detector order in ICARUS to change.
The order was customised for ICARUS, but the new channel mapping included a new sorting which used the "standard" LArSoft sorting for `AuxDetGeo` and `AuxDetSensitiveGeo` objects (i.e. CRT modules and submodules).
This commit moves the sorting code of PMT and of CRT out of the geometry sorters, and makes both sorters call the old CRT sorting so refactored (the new sorter also calls the PMT new sorting algorithm).
> Updated CRT geometry sorting (and mapping)

- fcl/configurations/showerfindermodules_icarus.fcl
- fcl/reco/reco_icarus.fcl
Do not delete branch after PR is finalized!!
This commit fixes typos in the standard "default" shower config that's there (in one place was written sbn and in the other sbnd. Also it said ShowerTools: when it should have said ShowerFinderTools:)
This commit also adds an intermediate shower reco configuration and an 'advanced' shower reco configuration. The reco fcl is still set up to do the 'default' one, but we may want to switch to one of the more advanced ones... I do have a couple questions to ask Ed/Dom offline, even about the intermediate one. However, right now the intermediate one seems to at least work and give dE/dx values. The advanced one DOESN'T work right now -- the Bayes tool has a bug in fcl params. This can be fixed easily in the job fcl. More problematic is that the …
> Patch typos in shower reco config and add two additional ones that we might consider switching to!

- fcl/services/photpropservices_icarus.fcl
- icaruscode/PMT/photon_propogation_timing_icarus.fcl
Scintillation photon propagation timing updated as for SBND experts recommendation.
This ends up being a cosmetic change only, since effectively the parameters in this commit are the same as the ones currently present in LArSoft.
> Updated photon propagation timing parameters: from SBND

- icaruscode/Geometry/CMakeLists.txt
- icaruscode/PMT/OpReco/FlashFinder/CMakeLists.txt
Reported by Bruce Howard.
It may have escaped our watch because depending on whether other packages are checked out in the same working area.
> Fixed linking issues with `icaruscode` standalone.

- CMakeLists.txt
- icaruscode/Analysis/tools/BasicRawDigitAnalysis_tool.cc
- icaruscode/CRT/CRTDecoder/AnaProducer_module.cc
- icaruscode/CRT/CRTDecoder/CrtCal.cc
- icaruscode/CRT/CRTTruthMatchAnalysis_module.cc
- icaruscode/CRT/CRTUtils/CRTDetSimAlg.cc
- icaruscode/Decode/DaqDecoderICARUSPMTold_module.cc
- icaruscode/PMT/Algorithms/DiscretePhotoelectronPulse.cxx
- icaruscode/PMT/Algorithms/PhotoelectronPulseFunction.h
- icaruscode/PMT/SinglePhotonPulseFunctionTool.h
- icaruscode/PMT/Trigger/Algorithms/details/EventInfoUtils.h
- icaruscode/TPC/Simulation/SpaceCharge/SpaceChargeICARUS.cxx
- ups/product_deps
Once the new larsoft release (and new sbncode release) comes out, we should have sbndaq_artaq_core build separately and setup via sbncode --> can remove the dependency in icaruscode.
> sbndaq_artdaq_core direct dep removal, plus some c7 compile fixes

- icaruscode/Decode/DecoderTools/decodertools.fcl
- icaruscode/Decode/decoder.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/CMakeLists.txt
- icaruscode/TPC/SignalProcessing/RecoWire/Decon1DROI_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/recowire_icarus.fcl
Add a module which will allow for 2D methods for finding ROIs on deconvolved waveforms. Idea is to accept as input a collection of full length deconvolved waveforms (no ROI finding) and then select the ROIs based on 2D methods. Currently only a 2D morphological filter technique is used but should be able to extend this.
> Add a 2D ROI finder module operating on deconolved waveforms and bug fix

- icaruscode/Decode/stage0_icarus_defs.fcl
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-decode-to-sig.jsonnet
Add the wirecell 2D deconvolution in the stage0 configuration. Two data products of recob::Wire are available: `decon2droi:gauss` and `decon2droi:wiener`. They are derived with different software filters, usually the `decon2droi:gauss` can be fed to the gaus hit finder.
Here is the consistency check between 1D and 2D decon:
> add wirecell decon into stage0

- fcl/gen/background/prodbackground_Ar39_icarus.fcl
> Minor change to 39Ar production FHiCL.

- icaruscode/PMT/Algorithms/pmtsimulation_icarus.fcl
Arbitrary, but motivated by the updated single photon response
(average amplitude 55 ADC).
This is a (mild) **breaking change** in terms of physics.
> Increased PMT digitisation threshold from 4 to 18 ADC counts.

- fcl/gen/corsika/corsika_icarus.fcl
ICARUS building wall currently (20201107) reaches up to y = +18.2 m.
Generation surface for CORSIKA has been increased by 2 m.
The accepted area on the detector has been proportionally extended.
This request is paired with pull request SBNSoftware/icarusalg#11 on geometry update.
> Cosmic ray generation altitude elevated by +10%.

- fcl/services/photpropservices_icarus.fcl
- icaruscode/PMT/scripts/CheckPhotonLibraryJobs.py
- icaruscode/PMT/scripts/MergePhotonLibrary.C
- icaruscode/PMT/scripts/neoSmazza202012.sh
This commit sets the default configuration of photon visibility (`PhotonVisibilityService`) to the photon library 20201209.
Relevant documentation about it is in the ICARUS wiki ([ICARUS wiki > Physics simulation > photon visibility map](https://sbnsoftware.github.io/icaruscode_wiki/physics/PhotonLibrary.html)) and on [SBN DocDB 19958](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=19958) version 2.
**This commit requires an update of `icarus_data` as well.**
(a copy of the new photon library can be currently found in ICARUS dCache at `/pnfs/icarus/persistent/users/petrillo/data/PhotonLibrary/PhotonLibrary-20201209.root`).
> Updated photon library (20201209)

- icaruscode/Utilities/CMakeLists.txt
- icaruscode/Utilities/DuplicateEventTracker.h
- icaruscode/Utilities/DuplicateEventTracker_service.cc
- icaruscode/Utilities/EventRegistry.cxx
- icaruscode/Utilities/EventRegistry.h
Jobs merging different input files may end up processing multiple events with the same ID.
Output files with duplicate events will throw exceptions when processed afterward.
I introduce a simple service, `DuplicateEventTracker`, which can detect duplicate events and by default throws an exception as soon as a duplicate event is seen. This draconian action is intended to inform the user of the problem when it's easier to be fixed.
> Added DuplicateEventTracker service

- fcl/gen/genie/filter_genie_active_icarus.fcl
- fcl/gen/genie/filter_genie_active_icarus_overburden.fcl
The job configuration in `filter_genie_active.fcl` contains ICARUS-specific details (i.e. geometry).
So I am renaming it to show it's ICARUS-specific.
Also, I have moved it into the common job configuration area.
> filter_genie_active.fcl renamed and moved.

- fcl/g4/intime_g4_icarus.fcl
- fcl/g4/intime_g4_icarus_sce_on.fcl
- fcl/g4/standard_g4_icarus.fcl
- fcl/services/simulationservices_icarus.fcl
While `standard_g4_icarus.fcl` and most related configurations set locally the option to same energy deposits into their output, the option, which is driven by `LArG4Parameters` service, was turned off by default.
Since `LArG4Parameters` is how some modules find out about the availability of energy depositions, this causes an inconsistency where energy depositions are available but user code is not aware of it.
This commit enables saving energy depositions in `LArG4Parameters`, which is what we want as general behaviour.
The standard `G4` job configurations do not override that setting any more, but rather they inherit its default (i.e. "enabled").
> Energy deposition storage from LArG4 enabled experiment-wide.

- icaruscode/Filters/CMakeLists.txt
After merging and reverting, trying again.
Note that this is already in `develop`, but was afterwards reverted in `master` only.
Previous pull requests: #125, #126 and #127.
> Take 3: added required library into FilterNeutrinosActiveVolume link list

- fcl/gen/corsika/prodcorsika_protononly_icarus.fcl
- fcl/gen/genie/prodcorsika_genie_protononly_icarus.fcl
- fcl/gen/numi/prodcorsika_genie_protononly_icarus_numi.fcl
These commits add job configurations to generate cosmic rays from proton primary only, as opposed to using the Constant Mass Composition which is the model of choice in the current `standard` ICARUS configuration:
* `prodcorsika_protononly_icarus.fcl` (background: cosmic rays only)
* `prodcorsika_genie_protononly_icarus.fcl` (BNB neutrino interactions)
* `prodcorsika_genie_standard_icarus_numi.fcl` (NuMI neutrino interactions)
All configurations are equivalent to the corresponding `standard` ones except for the cosmic ray model.
> Added configurations for cosmics and BNB + cosmics, proton primary only.

- fcl/utilities/dump_pmtconfig_icarus.fcl
- icaruscode/Decode/CMakeLists.txt
- icaruscode/Decode/DumpPMTconfiguration_module.cc
A job configuration extracting and then dumping the PMT configuration is provided as `dump_pmtconfig_icarus.fcl`.
> Added module to dump PMT configuration from data files.

- fcl/reco/reco_icarus.fcl
- icaruscode/Decode/DecoderTools/PMTDecoder_tool.cc
- icaruscode/Decode/stage0_raw_single_icarus.fcl
- icaruscode/Decode/stage0_single_icarus.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/Decon1DROI_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/DeconTools/BaselineMostProbAve_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/DeconTools/BaselineStandard_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/DeconTools/FullWireDeconvolution_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/DeconTools/IBaseline.h
- icaruscode/TPC/SignalProcessing/RecoWire/DeconTools/NoBaseline_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/DeconTools/ROIDeconvolution_tool.cc
Covering a few unrelated topics here:
1) Apply a mask to the PMT fragment ID before looking up in channel map database
2) Updates to the stage0, stage1 fhicl files for processing of unbiased trigger full readout data taking (and introduction of a file to run the "raw" signal processing after stage 0),
3) Addressing issue https://github.com/SBNSoftware/icaruscode/issues/136 by temporarily turning off the kalman track fit for the "icarus hit" path.
> Updates for interim release

- icaruscode/Decode/fcl/stage1_single_icarus_gauss.fcl
- icaruscode/Decode/fcl/stage1_single_icarus_gauss_pre091800.fcl
- icaruscode/Decode/fcl/stage1_single_icarus_gauss_v091800.fcl
Introducing two configurations for `stage1` processing of data decoded (i.e. `stage0`) with `icaruscode` `v09_18_00` or earlier.
Decoded files have a geometry recorded in them at `stage0`, and following processing must happen with the same geometry version.
With the breaking change in geometry on `v09_18_00`, data decoded with geometry pre-`v09_18_00` needs to be processed with a legacy geometry, which is what `stage1_single_icarus_gauss_pre091800.fcl` does.
Special special case is data decoded with `icaruscode` version `v09_18_00` and `v09_18_00_01` exactly, which have the new geometry but leave a track of using the old one. A special special configuration is necessary for processing these files (`fcl/stage1_single_icarus_gauss_v091800.fcl`).
> Stage1 configuration for data decoded with v09_18_00 or earlier

- fcl/services/services_common_icarus.fcl
This is a proposed solution for issue #147.
It adds `DuplicateEventTracker` service to the `icarus_art_services`, which is included in any ICARUS configuration even vaguely official. The configuration of the service is such that an exception is thrown on the first duplicate event encountered.
This is a GitHub commit (i.e. made with GitHub web editor).
> Added DuplicateEventTracker to default services

- scripts/runFilesFromSAM.sh
- scripts/sortDataLoggerFiles.py
I am offering two scripts that I ended up using quite often when processing data:
* `runFilesFromSAM.sh` creates a list of files which are already known to SAM, either from a run, a SAM definition, or bare file names; the entries in the list are paths that can be processed with _art_ via XRootD or other protocols;
* `sortDataLoggerFiles.py` creates a new file list sorting an existing one; the input file list is a list of ICARUS data files (may be raw, or processed, as long as they keep the file base name format of the raw file), and the output is a list where the first event of each file is expected to be lower then the one of the next file. In other words, it sorts the files in time.
Both scripts have options that can be learned by running them with `--help` option.
> Scripts for SAM/decoder file lists

- icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.cxx
- icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.h
- icaruscode/PMT/PMTWaveformBaselinesFromReadoutConfiguration_module.cc
The fragment ID needs now to be masked.
This fix is not needed if the suggestion in issue #151 is adopted (but since I need this to work _now_ I am pushing it anyway).
> Updated channel mapping access of PMT configuration extractor

- icaruscode/PMT/OpReco/fcl/icarus_opana_modules.fcl
- icaruscode/PMT/OpReco/fcl/icarus_spe.fcl
Gianluca reports failures of sim/recon with a missing fhicl definition for MCOptHit. This is meant to temporarily patch the problem until experts have time to consider an alternative (if one).
> Temporarily restore definition of Amplitude for MCOpHit

- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROICannyEdgeDetection_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROIMorphological2D_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/roiTools_icarus.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/recowire_icarus.fcl
Latest updates reflecting code changes in icarus_signal_processing. Canny Edge detection tool in icaruscode for running the edge finder on deconvolved waveforms. Default is still using the old 2D morphological filter approach.
> Canny Edge Detector updates

- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/Decode/fcl/stage0_icarus_driver_common.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_splitstream_east_icarus.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_splitstream_icarus.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_splitstream_west_icarus.fcl
- icaruscode/Filters/TriggerTypeFilter_module.cc
Include a filter function which can select between BNB and NuMI from the trigger data. Update the decoder stage0 fhicl files to use this filter in a "split stream" configuration (separate BNB and NuMI output streams) as well include two versions for single module running.
> Including trigger filter and updated decoder fhicl files

- fcl/utilities/list_duplicate_events.fcl
- scripts/sortDataLoggerFiles.py
In this pull request:
* new jon configuration file `list_duplicate_events.fcl` will list all duplicate events (based on event ID) in the input
* `sortDataLoggerFiles.py` updated to skip and print duplicate events when sorting a data file list
About `sortDataLoggerFiles.py`
----------------------------------------------
This utility sorts the files in a list so that their first event is in increasing order. It relies on ICARUS data file name convention.
Now it can also utilize its name parsing features to detect duplicate files in a list.
Duplicates file are file which stem from the same raw file (same run, same data logger cycle, same data logger).
By default, now duplicate files are skipped from the output, and their number (if any) is printed.
Options (`sortDataLoggerFiles.py --help`) …
> Added utilities to find duplicate files and events.

- icaruscode/Decode/fcl/decodePMT_icarus.fcl
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
Tested with run 5977 and `stage0_multiTPC_splitstream_icarus.fcl` only.
> Updated default PMT decoding configuration for multi-PMT readout

- icaruscode/Decode/BeamBits.h
- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
- scripts/sortDataLoggerFiles.py
The new decoder chooses the input data product from a list of possible candidates that is provided in the configuration.
If only one of them qualifies, then that one is chosen; otherwise an exception is thrown.
Currently for a input to "qualify", it needs to have data in it (empty fragment lists are not good enough, although a list of empty container fragments is ok).
Breaking change
------------------------
The input tag configuration parameter was changed from `FragmentsLabel` (a string) into `FragmentsLabels` (a list of strings).
Configurations will need to be updated (the standard ones have already).
> PMT decoding can autodetect the input type

- icaruscode/Decode/CMakeLists.txt
- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DecoderTools/CMakeLists.txt
- icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc
- icaruscode/Decode/DecoderTools/details/KeyedCSVparser.cxx
- icaruscode/Decode/DecoderTools/details/KeyedCSVparser.h
- icaruscode/Decode/DumpArtDAQfragments_module.cc
- icaruscode/Decode/fcl/decodePMT_icarus_standalone.fcl
- icaruscode/Decode/fcl/dump_artdaqfragments_pmt_icarus.fcl
This requests contains changes to the trigger and PMT decoding softare.
* bug fix: a default value was wrong (2 ns instead of 2 s)
* added some optional debugging information: dump the whole fragment content
The main feature being pursued here is the support for the "overlapping window" readout mode (the name is not official), which has been pioneered in run `6029`. In that mode, waveforms can come in packets shorter than the configured value (e.g. 30 µs) and they may come adjacent.
* major feature: support for waveforms of any size: timestamp is correctly computed including the actual waveform size
* adjacent waveforms (whose end and start match at less than 1 ns) are merged into a longer waveform
* more information in the optional debugging tree
* minor technical changes here and there …
> PMT decoder support for multi-window PMT readout

- icaruscode/PMT/Algorithms/pmtsimulation_icarus.fcl
ICARUS PMT readout window has been settled to 2 milliseconds in data, and this value is not being questioned.
So we can save some space and honour that choice.
> Updated PMT readout window

- test/ci/ci_tests.cfg
Change scaled cpu range for nucosmics_gen_quick_test_icaruscode from 200:603 to 200:653
Change memory range for single_reco_quick_test_icaruscode from 1000000:1500000 to 3000000:3800000
> Change memory and cpu ranges for ci tests

- icaruscode/PMT/Algorithms/pmtsimulation_icarus.fcl
When I changed the PMT readout window duration from 2.55 to 2.0 ms (commit e8effda), I did not change the _starting_ time of that window, that I should have.
The TPC readout window is 1.6 ms (4096×400 ns), covering from -340 µs before the trigger/beam to 1238 µs after it (see e.g. [SBN DocDB 18620, page 3](https://sbn-docdb.fnal.gov/cgi-bin/sso/RetrieveFile?docid=18620)).
The old settings with a window 2.55 ms long starting -1.15 ms before the trigger would cover from -1.15 to 1.4 ms.
The current settings with a window 2.0 ms long starting at -1.15 ms cover from -1.15 to 0.85 ms.
The proposed settings in this pull request are the ones _currently in use_ in the actual readout: with a window 2.0 ms long starting at -1.0 ms cover from -1.0 to 1.0 ms.
ASCII art time:
~~~
Trigger time scale …
> Fix the simulated PMT readout window position in time

- icaruscode/PMT/Trigger/Algorithms/details/TriggerInfo_t.h
- icaruscode/PMT/Trigger/MajorityTriggerEfficiencyPlots_module.cc
- test/PMT/Trigger/Algorithms/CMakeLists.txt
- test/PMT/Trigger/Algorithms/TriggerInfo_t_test.cc
- test/PMT/Trigger/CMakeLists.txt
A couple of fixed to trigger simulation.
I don't have a good perception of how one of them would affect the results.
The other affected the module creating plots from the majority trigger simulation (not the sliding window one, and not the majority trigger simulation module which just produces `raw::Trigger` objects), and would claim no trigger if one of the two cryostats had no channels at all. This could happen when channels from an entire cryostat were ignored upstream in the simulation.
> Some fixes to trigger simulation

- icaruscode/Decode/BeamBits.h
- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.h
- icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx
- icaruscode/PMT/Algorithms/PhotoelectronPulseFunction.h
- icaruscode/PMT/Trigger/Algorithms/CMakeLists.txt
- icaruscode/PMT/Trigger/Algorithms/ManagedTriggerGateBuilder.tcc
- icaruscode/PMT/Trigger/CMakeLists.txt
I am offering a few suggestions/recommendations for pull request #203 pertaining the code I am maintaining:
* `icaruscode/Decode/BeamBits.h`: the type declared for `names()` was wrong and should be replaced (rather than a correct one _added_)
* `icaruscode/Decode/DaqDecoderICARUSPMT_module.cc`:
* I personally prefer to move the definition of `icarus::DaqDecoderICARUSPMT::setBitIndices()` higher, in a section for templates
* the functionality of preventing narrowing (compiler will not build the code if narrowing would happen) is restored in `icarus::DaqDecoderICARUSPMT::extractTriggerTimeTag()`
* `icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.h`: `finalize()` method of base class is provided a definition (I have been fought on this for a while... not at all a strong opinion …
> Suggestions for pull request #203

- icaruscode/Analysis/overburden/OBAnaICARUS_module.cc
- icaruscode/CRT/CRTUtils/CMakeLists.txt
- icaruscode/Decode/BeamBits.h
- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DaqDecoderICARUSTPCwROI_module.cc
- icaruscode/Decode/DecoderTools/PMTDecoder_tool.cc
- icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.cxx
- icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.h
- icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc
- icaruscode/Decode/MCDecoderICARUSTPCwROI_module.cc
- icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx
- icaruscode/PMT/Algorithms/PhotoelectronPulseFunction.h
- icaruscode/PMT/Trigger/Algorithms/CMakeLists.txt
- icaruscode/PMT/Trigger/Algorithms/ManagedTriggerGateBuilder.tcc
- icaruscode/PMT/Trigger/Algorithms/SlidingWindowCombinerAlg.cxx
- icaruscode/PMT/Trigger/CMakeLists.txt
- icaruscode/PMT/Trigger/MajorityTriggerEfficiencyPlots_module.cc
- icaruscode/PMT/Trigger/Utilities/CMakeLists.txt
- icaruscode/TPC/SignalProcessing/RecoWire/CMakeLists.txt
- icaruscode/TPC/SignalProcessing/RecoWire/Decon1DROI_module.cc
1. Change in all `CMakeLists.txt` files is the same. Since `-Wno-maybe-uninitialized` is not supported by clang, it is made exclusive for GNU compiler
2. In `icaruscode/Analysis/overburden/OBAnaICARUS_module.cc` added override to funcion declaration
3. In `icaruscode/Decode/BeamBits.h` put names template in namespace
4. In `icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.h` deleted one return statement since it is declared in cxx
file
5. In `icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.cxx` and `icaruscode/PMT/Trigger/Algorithms/SlidingWindowCombinerAlg.cxx` removed std::move as redundand use
6. In `icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx` added template statemens to std::function around lumbda functions to make it work (review?)
7. In …
> c7:prof build cleanup

- fcl/detsim/commissioning/triggersim_icarus.fcl
- fcl/detsim/commissioning/triggersim_icarus_data.fcl
- fcl/utilities/find_duplicate_events.fcl
- icaruscode/Decode/BeamBits.h
- icaruscode/Decode/CMakeLists.txt
- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DataProducts/CMakeLists.txt
- icaruscode/Decode/DataProducts/ExtraTriggerInfo.cxx
- icaruscode/Decode/DataProducts/ExtraTriggerInfo.h
- icaruscode/Decode/DataProducts/classes.h
- icaruscode/Decode/DataProducts/classes_def.xml
- icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc
- icaruscode/Decode/DecoderTools/details/KeyedCSVparser.h
- icaruscode/Decode/fcl/CAEN_V1730_setup_icarus.fcl
- icaruscode/Decode/fcl/decodePMTdefs_icarus.fcl
- icaruscode/PMT/Trigger/Algorithms/SlidingWindowPatternAlg.cxx
- icaruscode/PMT/Trigger/CMakeLists.txt
- icaruscode/PMT/Trigger/Utilities/TriggerGateDataFormatting.h
- icaruscode/PMT/Trigger/scripts/CMakeLists.txt
- icaruscode/PMT/Trigger/scripts/triggeredEventList.py
- icaruscode/Utilities/CMakeLists.txt
- icaruscode/Utilities/DummyFilter_module.cc
- icaruscode/Utilities/DummyProducer_module.cc
- scripts/manageDataRunDefinitions.py
- scripts/sortDataLoggerFiles.py
This is a _large_ pull request containing several additions to PMT and trigger decoding, plus some utility modules, scripts and job configurations here and there.
The highlights:
* introduced a new data product `sbn::ExtraTriggerInfo` (still not fully finalised) that is expected to contain all the information from ICARUS trigger hardware and first processing, including absolute beam gate time
* the trigger decoder fills part of the new data product, _including the beam gate time_ (there is not enough information yet to fill the rest, with a couple of exceptions possible); PMT decoder utilises that data product as trigger information source
* the trigger decoder is now forgiving if the format of the raw trigger packet is corrupted, allowing the processing of some runs (`6017`-`6043`) that …
> Updates to PMT and trigger decoding

- icaruscode/PMT/Trigger/Utilities/TriggerGateDataFormatting.h
Clang is over-helpful in telling when construction of object via aggregate initialisation is _suspicious_.
A lot of characters after, it's not as suspicious any more.
Trying to avoid the double braces syntax because that is clearer only to Clang.
> Making Clang happier.

- icaruscode/Decode/ChannelMapping/ICARUSChannelMapProvider.cxx
- icaruscode/Decode/ChannelMapping/ICARUSChannelMapProvider.h
- icaruscode/Decode/ChannelMapping/IICARUSChannelMap.h
- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
The PMT decoder can't work without the mapping from fragment ID to off-line channel number which `IICARUSChannelMapping` is providing.
It has now changed to throw an exception at begin of the job when no PMT fragment ID is known to the service at all.
Since the service itself was not providing that information, the service (provider) interface and implementation was updated too.
> PMT decoder now throws an exception if PMT channel DB is empty

- icaruscode/Decode/DaqDecoderICARUSTPCwROI_module.cc
- icaruscode/Decode/MCDecoderICARUSTPCwROI_module.cc
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
- icaruscode/Decode/fcl/decoderdefs_mc_icarus.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_icarus_MC.fcl
- icaruscode/Decode/fcl/stage1_multiTPC_icarus_gauss_MC.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/Decon1DROI_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/IROILocator.h
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROICannyEdgeDetection_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROIFromDecoder_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROIMorphological2D_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/roiTools_icarus.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/recowire_icarus.fcl
Updates in the pull request will allow for processing of TPC detector simulation output through the same processing chain as the data with the caveat that it will take as the "raw" input the RawDigits from the detector simulation (so skips the actual "decoding" of the data but otherwise performs all the same steps with the same code). 
In addition, the decoder step now outputs the ROIs determined from the raw images during the noise processing in the form of "wire" data. This is then picked up by a new "ROI Finding" tool which runs after the deconvolution  to form ROIs for the deconvolved waveforms too.
> Updates to stage 0 processing for both data and simulation

- fcl/reco/reco_icarus_driver_reco_multitpc_gauss_sce_July2021.fcl
I prepare this fhicl in order to run MC productions in a similar way as previously done, I mean with reco1 and reco2 stages, but with the new labels required by the RawDigitFilter
> new reco1 stage for MC productions with new daq label in RawDigitFilter

- icaruscode/CMakeLists.txt
- icaruscode/IcarusObj/CMakeLists.txt
- icaruscode/IcarusObj/SimEnergyDepositSummary.h
- icaruscode/IcarusObj/classes.h
- icaruscode/IcarusObj/classes_def.xml
- icaruscode/PMT/Trigger/Algorithms/details/EventInfoUtils.cxx
- icaruscode/PMT/Trigger/Algorithms/details/EventInfoUtils.h
- icaruscode/PMT/Trigger/CMakeLists.txt
- icaruscode/PMT/Trigger/ExtractEnergyDepositionSummary_module.cc
- icaruscode/PMT/Trigger/MakeTriggerSimulationTree_module.cc
- icaruscode/PMT/Trigger/TriggerEfficiencyPlotsBase.cxx
- icaruscode/PMT/Trigger/TriggerEfficiencyPlotsBase.h
The trigger simulation modules have been extended to support alternative ways to provide energy deposition information.
The motivation is that the source files might have dropped the information needed for the energy deposition because of data size; at the time of dropping, if a summary is created, the necessary information stays available for the next stages.
Two sources are now supported:
* `sim::SimEnergyDeposits` collections: all energy depositions, one by one;
* `sim::EnergyDepositionSummary`: summary of the information from above.
Summary objects may be produced with the provided module, `ExtractEnergyDepositionSummary`, which supports the concepts of beam gate, pre-spill window and active volume. While the intended source to extract the summary information from is energy …
> Trigger simulation support using energy deposition summary

- icaruscode/TPC/ICARUSWireCell/icarus/wcls-decode-to-sig.jsonnet
Updated the configuration for the wirecell 2D deconvolution. Now if one runs `stage0_icarus_driver_common.fcl`, the full waveform after 2D deconvolution will be saved in label: `decon2droi:looseLf`. And one can apply the ROI on top of this waveform.
> save full 2d deconvolution waveform

- fcl/services/simulationservices_icarus.fcl
Change to Drop EM Shower daughters for the ICARUS G4 configuration.
> Don't keep shower daughters

- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/TPC/ICARUSWireCell/icarus/sp.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-decode-to-sig.jsonnet
I also added a configuration parameter `use_roi_refinement`. If it's set to `false`, it skips the ROI refinement in wirecell toolkit and reduces the memory usage. Note, our current plan is to use Tracy's and Dae's ROI, so it's fine for wirecell to skip its own ROI finding and refinement.
> extend decon2droi to full cryostats

- icaruscode/TPC/SignalProcessing/RawDigitFilter/TPCNoiseMC_module.cc
- icaruscode/TPC/SignalProcessing/RawDigitFilter/TPCNoise_module.cc
- test/ci/ci_tests.cfg
1)calibration adjustments for ci tests
2)In TPCNoiseMC_module.cc and TPCNoise_module.cc comment out beginRun() and endRun() (hidden overloaded virtual function) for c7
> CI calibration/c7 fix

- fcl/gen/numi/prodcorsika_genie_protononly_icarus_numi.fcl
- fcl/gen/numi/prodcorsika_genie_protononly_icarus_numi_nue.fcl
- fcl/gen/numi/prodcorsika_genie_standard_icarus_numi.fcl
- fcl/gen/numi/prodcorsika_genie_standard_icarus_numi_nue.fcl
They are `prodcorsika_genie_standard_icarus_numi_nue.fcl` and
`prodcorsika_genie_protononly_icarus_numi_nue.fcl`.
> Job configurations for NuMI electron neutrinos with cosmic rays

- fcl/services/simulationservices_icarus.fcl
This is the change needed to utilise the correlated ionisation/scintillation simulation by @wforeman ([SBN DocDB 17964](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=17964)) as standard for GEANT4 simulation.
The configuration is centralised enough that a change in a single place was needed.
This pull request will be a **draft** until a "all clear" message is sent by the collaboration.
> Model featuring correlated ionization and scintillation set as default

- icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel.jsonnet
change the output tag of simulated RawDigits from "daq:daq[0,1,2,3]" to "daq:TPC[EE,EW,WE,WW]".
> change output tag for wirecell sim rawdigits

- test/ci/ci_tests.cfg
- test/ci/icarus_ci_nucosmics_reco0_quick_test_icaruscode.fcl
- test/ci/icarus_ci_nucosmics_reco0_seq_test_icaruscode.fcl
- test/ci/icarus_ci_nucosmics_reco1_quick_test_icaruscode.fcl
- test/ci/icarus_ci_nucosmics_reco1_seq_test_icaruscode.fcl
- test/ci/icarus_ci_single_reco0_quick_test_icaruscode.fcl
- test/ci/icarus_ci_single_reco0_seq_test_icaruscode.fcl
- test/ci/icarus_ci_single_reco1_quick_test_icaruscode.fcl
- test/ci/icarus_ci_single_reco1_seq_test_icaruscode.fcl
The reco test is split into two tests.
reco0 is run with detsim input via stage0_multiTPC_icarus_MC.fcl
reco1 is run with reco0 input via stage1_multiTPC_icarus_gauss_MC.fcl
preliminary reference files are generated but need to be updated through Jenkins after merging  
old reco test is preserved, but disabled
> Split the reco test

- icaruscode/TPC/ICARUSWireCell/convert_Noise_ROOTtoJSON.py
- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel.jsonnet
Change in config/param files to incorporate a new noise model (per plane per TPC).
Add converter script to produce WireCell compatible .json.bz2 noise files from .root files
Simulation works with through : wirecell_multitpc_detsim_icarus.fcl (in icaruscode/fcl/detsim/)
PS. The extra commit is to restore the TPC volume names that occasionally got deleted in my branch
> New Noise Model Integration With WireCell

- fcl/gen/numi/prodcorsika_genie_protononly_icarus_numi_fullosc_volDetEnclosure_tpc.fcl
- fcl/gen/numi/prodcorsika_genie_protononly_icarus_numi_nue_volDetEnclosure_tpc.fcl
These fcls should enable the generation of a full osc and intrinsic nue-only samples for NuMI in the ICARUS detector. 
This should address https://github.com/SBNSoftware/icaruscode/issues/235
> Adding ICARUS NuMI Oscillation Fcls

- icaruscode/Decode/DaqDecoderICARUSTPCwROI_module.cc
- icaruscode/Decode/DecoderTools/INoiseFilter.h
- icaruscode/Decode/DecoderTools/TPCNoiseFilter1D_tool.cc
- icaruscode/Decode/DecoderTools/TPCNoiseFilterCanny_tool.cc
- icaruscode/Decode/MCDecoderICARUSTPCwROI_module.cc
- icaruscode/TPC/Simulation/DetSim/SimReadoutBoardICARUS_module.cc
- icaruscode/TPC/Simulation/DetSim/SimWireICARUS_module.cc
- icaruscode/TPC/Simulation/DetSim/tools/CorrelatedNoise_tool.cc
- icaruscode/TPC/Simulation/DetSim/tools/IGenNoise.h
- icaruscode/TPC/Simulation/DetSim/tools/NoNoise_tool.cc
- icaruscode/TPC/Simulation/DetSim/tools/NoiseFromHist_tool.cc
- icaruscode/TPC/Simulation/DetSim/tools/RandomNoise_tool.cc
- icaruscode/TPC/Simulation/DetSim/tools/SBNDataNoise_tool.cc
- icaruscode/TPC/Simulation/DetSim/tools/SBNNoise_tool.cc
- icaruscode/TPC/Utilities/SignalShapingICARUSService_service.cc
- icaruscode/TPC/Utilities/SignalShapingICARUSService_service.h
Changes enabling the TPC detector simulation to output "all" channels associated to "boards" to enable the coherent noise simulation across 64 channels.
> Updates for coherent noise simulation

- fcl/services/simulationservices_icarus.fcl
This enables the LArQL (addressing https://github.com/SBNSoftware/icaruscode/issues/278) and makes the ICARUS simulation consistent with SBND (see PR https://github.com/SBNSoftware/sbndcode/pull/194)
I'll tag @ggamezdiego to review since I don't see Alessandro M on github
> Enabling LArQL for ICARUS 

- fcl/caf/cafmaker_defs.fcl
- fcl/caf/cafmakerjob_icarus_sce_evtw.fcl
- fcl/caf/cafmakerjob_icarus_sce_genie_and_fluxwgt.fcl
Update `cafmaker_defs.fcl`: 
Change "eventweight_genie3_sbn_A.fcl" to "eventweight_genie_sbn.fcl";
Add "eventweight_flux_sbn.fcl"
> Updates FHiCLs for CAF to read weights from SBNEventWeight moduls in sbncode

- icaruscode/TPC/Tracking/ICARUSPandora/scripts/PandoraSettings_Neutrino_ICARUS.xml
This PR is a one line commit, but I made it separate since I'm more hesitant about this one. More info below.
@SFBayLaser  - I wasn't sure who the reviewer(s) should be. Can you assign folks that you think would be good to chime in?
**Info:**
This is probably really considered a bug-fix. My understanding (thanks to Ed for giving me the run-down on the change and to Henry for looking into this for SBND originally) is that since the Vertex BDT has features that use the initial characterization, this "ZeroMode" at the beginning of the vertexing algorithms is not desired (since it removes the initial characterization).
However, this is has only been looked at a little bit in ICARUS, and so I think the effects of it (positive/negative) are not very well understood at this point. Hence the …
> Second (more hesistant) PR relating to Reco/ICARUS Pandora updates

- fcl/caf/cafmaker_defs.fcl
- fcl/caf/cafmakerjob_icarus.fcl
- fcl/caf/cafmakerjob_icarus_data.fcl
- fcl/caf/cafmakerjob_icarus_evtw.fcl
- fcl/caf/cafmakerjob_icarus_nocaf.fcl
- fcl/caf/cafmakerjob_icarus_sce.fcl
- fcl/caf/cafmakerjob_icarus_sce_genie_and_fluxwgt.fcl
Add fhicl that is basically a copy of `cafmakerjob_icarus.fcl` but nullifies a some labels and a list of labels that belong to the simulation:
> physics.producers.cafmaker.G4Label: ""
> physics.producers.cafmaker.GenLabel: ""
> physics.producers.cafmaker.SimChannelLabel: ""
> physics.producers.cafmaker.SystWeightLabels: []
and makes it use a `caf_ana_data_sequence` which is the same as `caf_ana_sequence` removing the `mcreco` instance.
Tested that it ran over a few data events in v09_37 and produced a CAF file with some of the reco branches filled that I'd expect to be filled for data.
I'm tagging Gray and Chris B as reviewers here, and in fact have a question for each:
* Chris B: the resulting CAF file had many (33?) `globalTree` s -- is that expected?
* Gray: are there preliminary data …
> Data-handling CAFMaker script(s)

- icaruscode/PMT/scripts/neoSmazza.sh
The hard-coded geometry boundaries have been updated to reflect the current geometry (`icarus_v3`).
The script name has lost its date since the new version has not been used for any library yet.
> Updated photon library generation script geometry boundaries

- icaruscode/TPC/Simulation/SpaceCharge/SpaceChargeICARUS.cxx
This update should fix SCE simulation for ICARUS following a shift in the cathode location for both cryostats.  It should be verified with a MC sample of > 20k cosmic events, which I can carry out once the sample is available.
> Updating cathode location in SpaceCharge module

- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-decode-to-sig.jsonnet
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
The ROI finder needed one more bug fix in order to work correctly, after that the scale factor needed an adjustment so that the "standard" parameters in the ROI finder and gauss hit finder would not result in too many hits. Finally adjust the definitions in the fcl files so allow switching to 2D deconvolution if desired.
> Updates to enable running of 2D deconvolution

- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
Update Garfield simulation in WireCell with new bias voltages
The change comes with updated file in icarus_data
> Update WireCell Garfield simulation

- icaruscode/Decode/DecoderTools/CMakeLists.txt
- icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.cxx
- icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.h
- icaruscode/Decode/PMTconfigurationExtraction_module.cc
- icaruscode/Utilities/ReadArtConfiguration.h
It should be more resilient to art changes, and might also work in the online monitor.
In particular, I have added a utility to extract the configuration from `art::Run` (or `art::Event`, or `canvas::Event`) instead of directly from the _art_/ROOT input file, and the module uses this new utility.
The issue with the online monitor was that it gets its data from a stream so it does not have a input file; this new approach _might_ work since the input stream does have _art_ runs (whether they hold configuration or not is a different question).
> Refurbished PMT readout configuration discovery code.

- CMakeLists.txt
- icaruscode/Analysis/TPCPurityInfoAna_module.cc
- icaruscode/Analysis/TPCPurityMonitor_module.cc
- icaruscode/Analysis/analysis_icarus.fcl
- icaruscode/Decode/DaqDecoderICARUSTPC_module.cc
- icaruscode/Decode/DaqDecoderICARUSTPCwROI_module.cc
- icaruscode/Decode/DecoderTools/INoiseFilter.h
- icaruscode/Decode/DecoderTools/TPCNoiseFilter1D_tool.cc
- icaruscode/Decode/DecoderTools/TPCNoiseFilterCanny_tool.cc
- icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
- icaruscode/Decode/MCDecoderICARUSTPCwROI_module.cc
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
- icaruscode/Decode/fcl/stage0_icarus_mc_defs.fcl
- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
- icaruscode/TPC/SignalProcessing/RecoWire/Decon1DROI_module.cc
- ups/product_deps
Sorry to combine two relatively independent things! 
1) The 1d drift simulation outputs all channels to its RawDigits, including those that are not physical. This matches the data and enables the coherent noise subtraction to work without having to otherwise know that there are only 32 channels that are real. Probably this is something that needs to be addressed... Meanwhile, the 2d simulation only outputs "live" channels with the result that the process of decoding and coherent noise subtraction was causing some channels to be "lost". This PR introduces a way to recognize when this is happening and to patch those channels back in. Note this required a bit of interface modifications in order to allow to change the number of channels to use in the coherent noise subtraction on the fly. 
2) …
> Updates to decoder for 2d simulation and introduction of purity monitor module

- icaruscode/PMT/Algorithms/pmtsimulation_icarus.fcl
- icaruscode/PMT/AsymExpPulseFunctionTool_tool.cc
The interface of the current single photon response (SPR) has been updated to receive the PMT gain as a parameter to determine the expected amplitude of the signal.
At the same time, the parameter is now also shared (via common configuration definition) with the gain fluctuation simulation.
Breaking change
================
There is no really breaking change in physics, but there will be changes.
So ok, yes, it is a breaking change.
The amplitude of the single photon response is slightly changed (O(0.1%)) because of rounding.
Also the gain used as a reference to compute the fluctuations is changed (sensibly: from 10^7^ to 7 10^6^), which scales down all the gains from all PMT stages down. As the gain of the first stage, leading the fluctuation, decreases, its _relative_ Poisson uncertainty …
> Explicit setting for PMT gain

- icaruscode/PMT/OpReco/fcl/icarus_ophitfinder.fcl
Optical hit pedestal algorithm changed as in [SBN DocDB 24969](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=24969).
This changes the _default_ settings for all ICARUS jobs using standard optical hit reconstruction (for both data and simulation)
by changing `icarus_ophit` configuration.
This is one of the products of Winter 2022 ICARUS PMT "task force".
One point of attention to the reviewers is the following: these changes have been tested on data. Not so on simulation. We have evidence that the change does affect the simulation as well, but we haven't studied those changes.
Having a different reconstruction algorithm for simulation and data in part defeats the purpose of simulating reconstruction; but the waveforms are already so different that having the same reconstruction …
> Optical hit pedestal algorithm changed as in SBN DocDB 24969 (SBN2022A)

- icaruscode/Decode/DataProducts/ExtraTriggerInfo.cxx
- icaruscode/Decode/DataProducts/ExtraTriggerInfo.h
- icaruscode/Decode/DataProducts/classes_def.xml
- icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc
The trigger timestamp ultimately comes from the White Rabbit system, which has its time in [International Atomic Time (TAI) standard](https://en.wikipedia.org/wiki/International_Atomic_Time). To properly correct it into the UTC standard we adopted for timestamps some second offsets are necessary.
These are applied the first time by the trigger "board reader" during event building, and the result is currently used to attribute the trigger fragment and the _art_ event an absolute time. The trigger decoder in `icaruscode` also performed (presumably) the same correction as a workaround for a past issue, but a few months ago it went off-sync with the board reader.
This change ultimately trusts the board reader time and rather than attempting to apply the same correction, it learns it from the …
> Fixed absolute trigger timestamp in trigger decoder [SBN2022A]

- icaruscode/Decode/fcl/stage1_produce_calibtuples_MC.fcl
- icaruscode/Decode/fcl/stage1_produce_calibtuples_MC_numi.fcl
- icaruscode/Decode/fcl/stage1_produce_calibtuples_data.fcl
- icaruscode/Decode/fcl/stage1_produce_calibtuples_data_numi.fcl
Add fcl files to produce calibration ntuples separately from rest of stage1, runs on produced stage1 files. Tested on run 7033 BNB and NuMI data and also small numbers of NuMI cosmic MC and shown to reproduce both TPC and PMT calibration ntuples.
> Produce calibration ntuples independent of stage1 [SBN2022A]

- fcl/detsim/standard_detsim_icarus.fcl
- icaruscode/Analysis/ICARUSPurityDQM_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/recowire_icarus.fcl
- icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
- icaruscode/TPC/Tracking/cluster3D/cluster3dalgorithms_icarus.fcl
- icaruscode/TPC/Utilities/signalservices_icarus.fcl
This PR includes items for 1) deactivating the code block that was doing the ROI baseline correction, 2) includes the ability to produce "mythical" space points - those comprised of 2 spaces points - and 3) an update to the TPC purity monitor code from Christian to address failures that were causing production jobs to crash.
> TPC related updates for the SBN2022A production release

- icaruscode/CRT/CRTDataAnalysis_module.cc
- icaruscode/CRT/CRTUtils/CRTHitRecoAlg.cc
There used to be a 1sec difference between the gate_start_timestamp and T0 of CRTHit, but this was updated in https://github.com/SBNSoftware/icaruscode/pull/373.
We now don't need manual shifts when applying the timing cuts on CRTData. This should be merged before the production starts.
> 1sec shift is now removed between gate_start_timestamp and CRTHit T0

- fcl/caf/cafmaker_defs.fcl
Trigger label is added in `fcl/caf/cafmaker_defs.fcl`. This is related to https://github.com/SBNSoftware/sbncode/pull/251
> Trigger label added in fcl/caf/cafmaker_defs.fcl

- icaruscode/Decode/DataProducts/ExtraTriggerInfo.cxx
- icaruscode/Decode/DataProducts/ExtraTriggerInfo.h
- icaruscode/Decode/DataProducts/classes_def.xml
- icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc
This is the twin pull request of #373, this one against `develop`.
This pull request includes those same changes (in fact, same commit), plus the removal of the vestigial `Offset` parameter, as announced in that very pull request.
Commit list, courtesy of `gh`:
- Fixed absolute trigger timestamp in trigger decoder
- Removed "Offset" configuration parameter from trigger decoder
> Fixed absolute trigger timestamp in trigger decoder

- fcl/configurations/cluster_icarus.fcl
- icaruscode/Analysis/ICARUSPurityDQM_module.cc
- icaruscode/Analysis/tools/SpacePointAnalysis_tool.cc
- icaruscode/Decode/fcl/stage1_multiTPC_icarus_gauss_MC.fcl
- icaruscode/TPC/Tracking/cluster3D/CMakeLists.txt
- icaruscode/TPC/Tracking/cluster3D/Cluster3DICARUS_module.cc
- icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
- icaruscode/TPC/Tracking/cluster3D/cluster3dalgorithms_icarus.fcl
These are primarily aimed at solving issues seen by the ML reconstruction effort:
1) Import the Cluster3D module to modify so it does not overwrite the 2 hit space point "chi2" with a set number
2) Remove the restriction that a hit cannot have been used to make a 3 hit space point. This was killing exactly the space points we were trying to recover! 
The 2 hit space point volume is a bit concerning and still to be watched.
> Updates to the space point building

- icaruscode/PMT/OpReco/ICARUSFlashAssAna_module.cc
A message suggesting that the optical flash data product was not found was printed even when the data product was there but empty. Example:
```
%MSG-e ICARUSFlashAssAna:  ICARUSFlashAssAna:simpleLightAna@BeginModule  23-Mar-2022 13:14:22 CDT
run: 7033 subRun: 1 event: 192799
Not found a recob::OpFlash with label 'opflashCryoE'
%MSG
%MSG-e ICARUSFlashAssAna:  ICARUSFlashAssAna:simpleLightAna@BeginModule  23-Mar-2022 13:14:22 CDT
run: 7033 subRun: 1 event: 192799
Not found a recob::OpFlash with label 'opflashCryoW'
%MSG
```
This fix prints a different message in case the data product is not found and in case it is empty.
This is a GitHub change, I did not compile it and count on the integration test to do it for me.
> Changed misleading message in ICARUSFlashAssAna

- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DecoderTools/details/PMTDecoderUtils.cxx
- icaruscode/Decode/DecoderTools/details/PMTDecoderUtils.h
- icaruscode/Decode/fcl/CAEN_V1730_setup_icarus.fcl
- icaruscode/Decode/fcl/decodePMT_icarus.fcl
This changes in the PMT decoder allow the decoding of the 24 PMT readout channels that are not associated to any channel ID in the PMT channel mapping database.
Each special channel must be explicitly configured in the FHiCL configuration in the module in order to be decoded.
The special channels can be written only if on global trigger time, only if there is signal on them, or always, and they can be redirected to a different data product (instance name) than the one for the "regular" channels.
The configuration provided as default for "Run1" includes:
* all the standard channels, as usual, in the data product `daqPMT` with no instance name
* 8 waveforms per trigger primitive, into the `daqPMT:trgprim` data product, with the digitization of the trigger primitive signal as entering the …
> Decode special PMT readout channels

- icaruscode/Decode/fcl/stage0_multiTPC_rawpmt_icarus_MC.fcl
- icaruscode/PMT/OpReco/fcl/icarus_ophitfinder.fcl
It has been decided to revert the optical hit baseline algorithm choice to the "old" one tuned a couple of years ago _only in simulation_, because the new one that works well with data does not do the same with simulation.
This pull request attempts to sever the two configurations (data and MC) by defining two template configurations (`icarus_ophit_data` and `icarus_ophit_MC`) that job configurations can pick appropriately.
As the name implies, this pull request is meant to be included in the release for the SBN2022A production.
Stage0 configuration is by default designed for data, and optical reconstruction settings are taken from the "data" configuration (`icarus_ophit_data`). This was true also before this pull request, which effectively just introduces only the `MC` variant.
The …
> New optical hit baseline algorithm for data, old for MC [SBN2022A]

- icaruscode/Decode/DecoderTools/details/KeyedCSVparser.cxx
- icaruscode/Decode/DecoderTools/triggerPacketParser.cxx
The key-value parser can be used to parse a string in the type of format that the trigger hardware uses to communicate its data.
The format is a comma-separated list of words, some of them are keys, and then their values follow.
The parser is intended to be generic and as such it needs some heuristic to figure out whether a work is a key or not. The heuristic currently implemented fails miserably when the value is a hexadecimal number starting with a letter (e.g. `deadbeef`), and to address this the parser allows to specify custom patterns declared to be keys, and how many values such key have.
For example, a string `Hex1, deadbeef, Hex2, a10e, Value, 9` can be parsed specifying that both `Hex1` and `Hex2` (regex pattern `Hex[12]`) are key requiring one value. If this step is omitted, …
> Fix on key-value CSV file parser

- scripts/runFilesFromSAM.sh
Feature added to `runFilesFromSAM.sh`.
This script queries SAM database for a run or a definition and fills a file list with paths to the files in that run or definition.
This change allows to limit the number of files put in the file list even when querying a SAM definition (before only the run queries supported this).
Review notes: I don't think this requires a review.
> runFilesFromSAM.sh can now translate only part of a SAM definition

- icaruscode/Decode/DataProducts/ExtraTriggerInfo.cxx
Very minor fix (the time correction was 2-complemented when dumping the object to an output stream, instead of 36.0 it looked like 2⁶⁴/1e9 - 36).
Review not really needed.
> Fixed faulty printout of sbn::ExtraTrigInfo

- icaruscode/CRT/CRTUtils/CRTHitRecoAlg.cc
This PR is related to https://github.com/SBNSoftware/sbnobj/pull/52.
- When looking at https://github.com/SBNSoftware/sbnobj/blob/v09_13_12/sbnobj/Common/CRT/CRTHit.hh#L49-L50, `sbn::crt::CRTHit::ts0_ns` and `sbn::crt::CRTHit::ts1_ns` should be the last 9 digits of the full timestamp in ns, but we've been saving the entire timestamp to them. This is fixed in this PR.
- Also, the 1 second shift in the trigger time is (or will be? @jzettle) fixed in the recent data, so the corresponding manual-shift is removed in the CRTHit reconstruction. This part has been already applied in the [release/SBN2022A](https://github.com/SBNSoftware/icaruscode/tree/release/SBN2022A) branch by https://github.com/SBNSoftware/icaruscode/pull/384.
> Update CRTHit timing structure

- icaruscode/TPC/ICARUSWireCell/icarus/nf.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/sim.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/sp.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-decode-to-sig.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-omit-noise.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-sim-drift-simchannel.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wct-coherent-noise.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wct-sim-check.jsonnet
Updated wirecell configuration files to work with new Noise Model;
Extra changes involve adapting to the new WC version. Thus, should be merged ONLY with WC 0.18.1 (and corresponding larwirecell)
Noise mode comes in separate PR to icarus_data
> Update WireCell configs

- icaruscode/CRT/CRTDataAnalysis_module.cc
- icaruscode/Decode/fcl/stage1_icarus_defs.fcl
- icaruscode/Decode/fcl/stage1_multiTPC_icarus_gauss.fcl
- icaruscode/Decode/fcl/stage1_multiTPC_nofilter_icarus_gauss.fcl
This pull request adds the CRTHit information into the calibration ntuples using a CRTDataAnalysis module that was already in place from the ICARUS CRT group. The solution might be a bit klugey due to my fcl inexperience. Will happily take suggestions but this worked on the stage1 processing on a BNB data file from ICARUS, run 7926 on both stage1 fcl paths tested and could access CRTHit information. Adding people I think would want to know about this as reviewers.
> Include CRTHits in calibration ntuples

- icaruscode/CRT/CRTDataAnalysis_module.cc
- icaruscode/Decode/fcl/stage1_icarus_defs.fcl
- icaruscode/Decode/fcl/stage1_multiTPC_icarus_gauss.fcl
- icaruscode/Decode/fcl/stage1_multiTPC_nofilter_icarus_gauss.fcl
Identical changes to https://github.com/SBNSoftware/icaruscode/pull/399 but changes made to release/2022A branch so this is included in production. Tested again on a few events in ICARUS BNB data file, run 7926 and able to print out information from CRTHits.
> CRTHit Trees in calibration ntuples [release/SBN2022A]

- icaruscode/Decode/BeamBits.h
- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DataProducts/ExtraTriggerInfo.cxx
- icaruscode/Decode/DataProducts/ExtraTriggerInfo.h
- icaruscode/Decode/DataProducts/classes_def.xml
- icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.cxx
- icaruscode/Decode/DecoderTools/TriggerDecoderV2_tool.cc
- icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/Decode/fcl/stage0_icarus_defs_olddata.fcl
- icaruscode/Decode/fcl/stage0_icarus_driver_common_olddata.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_splitstream_nofilter_rawpmt_icarus.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_splitstream_nofilter_rawpmt_icarus_olddata.fcl
- icaruscode/Decode/fcl/test_trigger_decode.fcl
This PR adds the new trigger decoding framework to the develop branch. Same caveats as for the original PR to the production branch: https://github.com/SBNSoftware/icaruscode/pull/398 that it only works on data taken with the latest DAQ release or before the implementation of the new trigger system. In the near future I will create a separate branch to handle this data.
Tested with all 4 existing data streams with only the trigger decoder and also the full stage0 processing for run 8353
> Included new version of trigger decoder framework in development release

- fcl/utilities/dump_triggerconfig_icarus.fcl
- icaruscode/Decode/BeamBits.h
- icaruscode/Decode/CMakeLists.txt
- icaruscode/Decode/DataProducts/TriggerConfiguration.cxx
- icaruscode/Decode/DataProducts/TriggerConfiguration.h
- icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.cxx
- icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.h
- icaruscode/Decode/DumpTriggerConfiguration_module.cc
- icaruscode/Decode/TriggerConfigurationExtraction_module.cc
This request adds a `DumpTriggerConfiguration` module to print trigger configuration on screen.
The trigger configuration is expected to be stored into a data product, for which a producer module was recently introduced by @ascarpel.
This pull request also contains a few minor tweaks to the output of that data product on screen, and also indentation fixes and a missing function for `BeamBits.h`. Finally, it also moves the name of the trigger data fragment from hard-coded to a parameter.
Since @ascarpel is the original author of the code, I ask for his review.
> DumpTriggerConfiguration module to print trigger configuration on screen

- icaruscode/Decode/ChannelMapping/ICARUSChannelMapProvider.cxx
I have tested the new implementation by an intermediate version running the same query in the two ways and throwing on mismatch, and successfully running on 2 events. More testing may be desired.
The pattern that I replaced is also present in other parts of the code. This commit also includes a proposal for one of them, but my test did not call that part of the code so the proposed reimplementation was not really tested, which is the reason it stays as a comment.
In case this new implementation turns out being still too slow, further gain may be possibly achieved turning the map into a hash table (`std::unordered_map`).
> Reimplemented channel mapping query for side CRT.

- icaruscode/PMT/OpReco/ICARUSMCOpHit_module.cc
See for example [a 78 MB C.I. test log](https://dbweb8.fnal.gov:8443/LarCI/app/ns:icarus/storage/docs/2022/07/15/stdout%23wFKx93s.log) explaining what this means.
This is GitHub coding: untested!
> Removed ultra-spamming debug message from MC OpHit

- icaruscode/Decode/fcl/stage0_icarus_driver_common.fcl
- icaruscode/Decode/fcl/stage0_run1_icarus.fcl
- icaruscode/Decode/fcl/stage0_run1_icarus_lite.fcl
- icaruscode/Decode/fcl/stage0_run1_raw_icarus.fcl
- icaruscode/Decode/fcl/stage0_run1_raw_icarus_lite.fcl
- icaruscode/Decode/fcl/stage0_run1_rawpmt_icarus.fcl
- icaruscode/Decode/fcl/stage0_run1_wc_icarus.fcl
- icaruscode/Decode/fcl/stage0_run1_wc_icarus_lite.fcl
The daq system is now sending up the data separated by stream type (e.g. "BNB") and it is not longer necessary, or even possible, to filter the data at stage0. These fhicl files are meant to be used for running stage0 on data without filtering to streams. I have also taken this opportunity to try to rationalize the fhicl naming scheme a bit, removing some old terminology (e.g. "multiTPC") that really no longer has context. Hopefully "run1" is descriptive to the use here! 
I have tested in limited capacity on a sample BNB file provided to me.
> Creating "run1" fhicl files for stage0 processing of data

- icaruscode/Decode/DaqDecoderICARUSTPCwROI_module.cc
- icaruscode/Decode/DecoderTools/TPCDecoderFilter1D_tool.cc
- icaruscode/Decode/DecoderTools/TPCNoiseFilter1D_tool.cc
- icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/Decode/fcl/stage0_run1_wc_icarus.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/IROILocator.h
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROICannyEdgeDetection_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROIFromDecoder_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROIMorphological2D_tool.cc
- icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
The proposed plan for 2D deconvolution is to use the ROIs found in the 1D deconvolution and apply them to the 2D deconvolved waveforms. In principle this was already allowed but it seems was not totally functional so these updates make this chain work. As well there are modifications to the basic fhicl include file to allow this to work. 
In addition some small updates have been made to the noise filtering which are included in this pull request. These do not affect processing of waveforms, but should make event displays a bit cleaner (as the pedestal subtraction is slightly better).
> Updates to enable using 1D ROIs on 2D deconvolution, also noise filter updates

- icaruscode/Decode/DaqDecoderICARUSTrigger_module.cc
- icaruscode/Decode/DataProducts/TriggerConfiguration.h
- icaruscode/Decode/DecoderTools/TriggerDecoderV2_tool.cc
- icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
- icaruscode/Decode/fcl/decodePMT_icarus.fcl
- icaruscode/Decode/fcl/decodeTrigger_icarus.fcl
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
This request adds a couple of missing features to the trigger decoder and polishes the code.
I consider this the final release of the decoder for the current version of the trigger, barred fixes.
The added features:
1. the beam gate time is corrected for the artificial veto (currently, 4 µs) used to effectively extend the PMT readout ahead of the beam
2. the width of the gate is correctly saved in the `sim::BeamGateInfo` data product
3. support is added for calibration type of gates
The first two features leverage on the new module by @ascarpel which saves the configuration of the trigger in a data product, where both veto and beam gate duration are stored. This comes with the addition in all the relevant workflows of that module.
In addition, the documentation of the trigger decoder has …
> Trigger decoder final updates

- fcl/services/simulationservices_icarus.fcl
Somehow not inherited from `simulationservices.fcl`
Needed for https://github.com/LArSoft/larsim/pull/97
> Add value of ion+excitation work function

- icaruscode/TPC/ICARUSWireCell/detsimmodules_wirecell_ICARUS.fcl
- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel.jsonnet
- icaruscode/TPC/ICARUSWireCell/wcls-multitpc-sim-drift-simchannel.fcl
PR to change configurations to interface with new wc version 0.22.0
Allow intrinsic noise to be simulated from input histograms. Groups are set by board, but can be any
PS. icarus_data must be updated with new noise files . Check with @rennney if LArSoft has required changes before merge
> WireCell Noise Model Update

- icaruscode/Decode/DecoderTools/TriggerDecoderV2_tool.cc
I was not satisfied by the message that I was given on trigger parsing error.
This pull request makes the decoder print on console the whole string being parsed when the parser fails.
As a side, an additional identical parsing when diagnostics are required has been removed: diagnostics will show the same parsed data the trigger information is extracted from.
> Trigger decoder prints input on parsing error

- scripts/runFilesFromSAM.sh
- scripts/sortDataLoggerFiles.py
Minor changes to my scripts:
* `runFilesFromSAM.sh`:
* fixed a bug when no limit on file number is set
* added options to use SAMweb `locate-file` instead of `get-file-access-url`
* added option to specify the SAM station name ("experiment")
* `sortDataLoggerFiles.py`: in the discovery of the first data logger, stop when a file is found which contains the first event of the run
> Fixes to scripts to get run file lists from SAM

- icaruscode/CRT/CRTDecoder/CMakeLists.txt
- icaruscode/CRT/CRTDecoder/DecoderICARUSCRT_module.cc
- icaruscode/Utilities/ArtDataProductSelectors.cxx
- icaruscode/Utilities/ArtDataProductSelectors.h
- icaruscode/Utilities/CMakeLists.txt
These two commits are intended to reduce the memory footprint of Stage0 job.
1. The first commit uses a "selector" to decide which data products to look for CRT data, instead of trying all of them. The previous pattern loaded all the artDAQ fragment in memory instead. The net effect of this alone is a dramatic speed up in jobs decoding only CRT data, but little to no gain is expected by full Stage0 jobs, where most data will be loaded by the other decoders anyway.
2. The second commit enables dropping the data products (CRT data fragments) from the memory after use. This is a feature _art_ provides on demand (and currently only for data products from the _input file_), and since nothing else is ever expected to use this CRT data, no reload will follow. This is also not particularly …
> Memory footprint improvements related to CRT decoding

- fcl/caf/cafmakerjob_icarus.fcl
- fcl/caf/cafmakerjob_icarus_data.fcl
- fcl/gen/background/prodbackground_Ar39_icarus.fcl
- fcl/gen/corsika/prodcorsika_proton_intime_icarus_bnb.fcl
- fcl/gen/cosmics/simulation_cosmics_icarus_common.fcl
- fcl/gen/mevprtl/higgs/dissonant_higgs_gen.fcl
- fcl/gen/mevprtl/higgs/dissonant_higgs_tree_icarus.fcl
- fcl/gen/mevprtl/hnl/hnl_icarus_gen.fcl
- fcl/gen/mevprtl/hnl/hnl_testray_icarus.fcl
- fcl/gen/mevprtl/hnl/hnl_tree_icarus.fcl
- fcl/gen/single/prodsingle_common_icarus.fcl
- fcl/services/seedservice_icarus.fcl
- fcl/services/services_common_icarus.fcl
- fcl/services/services_icarus_simulation.fcl
The policy now uses `random` as fallback policy for per-event seeds.
This addresses issue #243.
The background: LArSoft provides a policy for providing seeds to the random number generators which ensures that the same event will always receive the same seeds, guaranteeing job reproducibility. Unfortunately that policy does not define what happens when seeds are required outside the event boundaries; a typical case is the LArSoft implementation of CORSIKA interface, `CORSIKAGen`, which _at beginning of the job_ decides randomly which pool of pre-generated events to use in the job. This choice happens at a time when no event is being processed (no input file, in fact, has been opened yet). The undefined behaviour of the per-event policy was in fact to always use `0` as a seed, which would …
> Random seed policy moved back to per-event

- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DecoderTools/TriggerDecoderV2_tool.cc
The field of `sbn::ExtraTriggerInfo` in charge of recording which type of trigger logic is applied (minimum bias, majority) is now correctly set from the decoded information.
Plain and simple, this bit had escaped us.
The PMT decoder tree now also stores that information.
We might also consider to set a bit in `raw::Trigger` with whether the trigger is minimum bias or not... but that is not for this time.
> Decoder now updates trigger type (minimum bias, majority)

- fcl/caf/cafmakerjob_icarus.fcl
- fcl/caf/cafmakerjob_icarus_data.fcl
- fcl/caf/cafmakerjob_icarus_evtw.fcl
- fcl/caf/cafmakerjob_icarus_sce_genie.fcl
- fcl/caf/cafmakerjob_icarus_sce_genie_and_fluxwgt.fcl
Recently I reworked the random number service configuration and at the same time removed the configuration of the random services from the places where it is not supposed to belong.
CAF making is one of them, since it's about translation of data from one format to another.
Unfortunately CAF making currently does more than just translation, and in particular for simulation input it runs a generation-class process, the stochastic extraction of generation parameters and the computation of the weights bridging the extracted parameters to the ones chosen by the experiment as the best ones. These jobs were broken by my changes.
This pull request simply adds the configuration of the required services to the two CAF making jobs including weight generation that I could find.
It is a non-breaking …
> Fixed CAF making jobs with generator systematics

- fcl/caf/cafmakerjob_icarus.fcl
Turn off newly added blinding code in cafmaker for MC since it's only needed for data. Added to cafmakerjob_icarus.fcl which should propagate to other MC cafmaker fcls.
> Turn off blinding in for MC cafmaker

- icaruscode/TPC/Calorimetry/NormalizeDriftSQLite_tool.cc
- icaruscode/TPC/Calorimetry/NormalizeTPCSQL_tool.cc
- icaruscode/TPC/Calorimetry/NormalizeYZSQL_tool.cc
Right now, running Calorimetry is really slow because access to the SQL database is slow. This speeds it up considerably.
> Cache requests to SQL database for TPC calibration

- fcl/reco/Stage1/Run2/stage1_run2_icarus_MC.fcl
- fcl/reco/Stage1/Run2/stage1_run2_wc_icarus_MC.fcl
Add CRT ntuple creator module to MC. This simply runs the same module that is run on the data to fill the ntuples. The reconstructed HitTree is filled and the module runs. Tested on what I understand is recent MC produced for testing WireCell, which is unrelated except for it was produced with a recent icaruscode version so this runs on the right MC for merging here.
> Add CRT ntuple creation module to MC

- CMakeLists.txt
- icaruscode/Analysis/trigger/CMakeLists.txt
- icaruscode/Decode/CMakeLists.txt
- icaruscode/TPC/Utilities/CMakeLists.txt
Add missing pkg_search_module needed by icarus_signal_processing target. Add missing link targets for header includes.
> Fix cmake and build errors found in standalone build of icaruscode v09_63_00

- CMakeLists.txt
- icaruscode/Analysis/trigger/CMakeLists.txt
- icaruscode/Decode/CMakeLists.txt
- icaruscode/TPC/Utilities/CMakeLists.txt
Add missing pkg_search_module needed by icarus_signal_processing target. Add missing link targets for header includes.
> Fix cmake and build errors found in standalone build of icaruscode SBN2022B

- fcl/reco/Definitions/CAEN_V1730_setup_icarus.fcl
This update reflects the configuration of PMT readout into the PMT decoder.
**This is high priority** as it affects Stage0 output.
And I am not sure who can review it.
Tested on a couple of Run2 events with `stage0_run2_icarus.fcl`.
> Updated configuration of special PMT readout channels [SBN2022B]

- fcl/reco/Definitions/stage0_icarus_defs.fcl
- fcl/reco/Stage0/Run2/stage0_run2_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_raw_icarus.fcl
This is the twin request of #504, but for production branch.
See PR #504 for the details.
> Stage0 configuration only keeps waveforms at beam gate time [SBN2022B]

- fcl/gen/genie/genie_icarus_bnb.fcl
Tune (chosen with the UPS qualifier of `genie`, currently `G1810a0211a:e1000:k250`) in GENIE v3 includes MEC, and the old event list should not be used any more.
Many thanks to @mmrosenberg, @sjgardiner and Stephen Dolan for the support.
> GENIE event generator list set back to Default

- fcl/reco/Definitions/decoderdefs_icarus.fcl
- fcl/reco/Definitions/stage0_icarus_defs.fcl
- fcl/reco/Stage0/Run2/partial/decodeTrigger_icarus.fcl
- icaruscode/Decode/DaqDecoderICARUSTrigger_module.cc
- icaruscode/Decode/DataProducts/TriggerConfiguration.cxx
- icaruscode/Decode/DataProducts/TriggerConfiguration.h
- icaruscode/Decode/DataProducts/classes_def.xml
- icaruscode/Decode/DecoderTools/CMakeLists.txt
- icaruscode/Decode/DecoderTools/IDecoder.h
- icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.cxx
- icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.h
- icaruscode/Decode/DecoderTools/TriggerDecoderDispatcher_tool.cc
- icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
- icaruscode/Decode/TriggerConfigurationExtraction_module.cc
This branch introduces and enables in the standard workflow a trigger decoding tool which is able to process trigger data fragments both from V2 (Run 1) and from V3 (Run 2).
Mixing the two is untested and may cryptically fail.
The new tool is actually just a dispatcher which will read from the run which version is being saved in the input file and will instantiate and utilise the proper single-version existing trigger decoder tool for processing.
In addition, the trigger configuration data product and extractor have been extended to discover and store which DAQ "generator" was used in the run, which then allows the new decoder tool to take the proper action.
Because ultimately the existing decoders are used for the actual processing, it is expected that no breaking change happens. The old …
> Trigger decoder tool supporting both V2 and V3 data fragment versions

- icaruscode/CRT/CRTT0MatchingAna_module.cc
- icaruscode/CRT/CRTT0Matching_module.cc
Replaces a now-faulty if statement to correctly search for the default value of DCA for the closest CRT Hit and skip if that default is found, which is a sign no match was found and thus will return null pointers that have caused seg faults.
> Fixing CRTT0Matching_module

- fcl/gen/mevprtl/higgs/dissH_corsikap_kdif_M050.fcl
- fcl/gen/mevprtl/higgs/dissH_corsikap_kdif_M100.fcl
- fcl/gen/mevprtl/higgs/dissH_corsikap_kdif_M150.fcl
- fcl/gen/mevprtl/higgs/dissH_corsikap_kdif_M200.fcl
These fcl files were added to a production branch of icaruscode (v09_37) in March 2022, and I would like them in develop also so that they continue to be accessible in later code releases.
> add kdif-only fcls for higgs portal generator

- fcl/configurations/beamgates_icarus.fcl
- fcl/gen/MultiVertex/multivertex_icarus.fcl
- fcl/gen/background/prodbackground_Ar39_icarus.fcl
- fcl/gen/corsika/prodcorsika_proton_intime_icarus_bnb.fcl
- fcl/gen/corsika/prodcorsika_proton_intime_icarus_numi.fcl
- fcl/gen/corsika/prodcorsika_standard_icarus.fcl
- fcl/gen/genie/prodcorsika_genie_standard_icarus.fcl
- fcl/gen/genie/simulation_genie_icarus_bnb.fcl
- fcl/gen/genie/simulation_genie_icarus_simple.fcl
- fcl/gen/mevprtl/higgs/dissonant_higgs_gen.fcl
- fcl/gen/mevprtl/hnl/hnl_icarus_gen.fcl
- fcl/gen/numi/simulation_genie_icarus_numi.fcl
- fcl/gen/numi/simulation_numi.fcl
- fcl/gen/numi/simulation_numi_nue.fcl
- fcl/gen/numi/simulation_numi_numu.fcl
- fcl/gen/overlay/prodoverlay_proton_sbnflux_icarus.fcl
- fcl/gen/single/prodsingle_common_icarus.fcl
- fcl/gen/text/prodtext_standard_icarus.fcl
- fcl/reco/Definitions/stage0_icarus_mc_defs.fcl
- icaruscode/PMT/Trigger/simulate_triggers_icarus.fcl
- icaruscode/PMT/Trigger/trigger_emulation_icarus.fcl
- icaruscode/PMT/Trigger/trigger_icarus.fcl
This pull request attempts to integrate trigger simulation in the standard production workflow, following PR #483 .
The general issue is that trigger emulation needs to know the beam gate, and it turns out that LArSoft generators do not fix a beam gate, except `GENIEGen` which fixes it wrong.
The strategy I propose adds to all generator jobs the creation of a beam gate with the module name `beamgate`. Downstream jobs will be able to learn the nominal beam gate by referring to that data product; trigger simulation does that (potentially it could also extend the gate to be closer to the hardware, but that's for a different pull request).
This pull request is made of two parts:
* reintroduction of trigger simulation in standard Stage0 MC workflow
* addition of a beam gate in pretty much all …
> Trigger simulation in production workflow

- fcl/reco/Definitions/decoderdefs_icarus.fcl
- fcl/reco/Definitions/stage0_icarus_defs.fcl
- fcl/reco/Stage0/Run2/stage0_run2_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_raw_icarus.fcl
Following PR #478, this pull request enables retaining only the waveforms including the beam gate.
Technically, all PMT decoding and reconstruction proceeds through the data product `daqPMT` as before, but a module is appended that copies the regular waveforms containing the regular beam gate opening time from `daqPMT` into `daqPMTonbeam`. Then the regular PMT waveforms from `daqPMT` are all dropped.
Note that this affects only the "regular" waveforms, i.e. the ones associated with a PMT. The waveforms on the other readout channels (the "16th channel") are in different data products and are retained.
This behaviour has been encoded in the default `Stage0` Run 2 job configuration `stage0_run2_icarus.fcl`.
The job configuration `stage0_run2_raw_icarus.fcl` has been modified not to run the …
> Stage0 configuration only keeps waveforms at beam gate time

- fcl/reco/Definitions/stage0_icarus_defs.fcl
- fcl/reco/Definitions/stage0_icarus_mc_defs.fcl
- icaruscode/PMT/OpReco/fcl/icarus_ophitfinder.fcl
- icaruscode/PMT/extractpmtchannelbaseline_icarus.fcl
A standalone algorithm, not directly used (yet) for optical reconstruction, computes the PMT waveform baselines based on all the recorded activity on a channel during a  single event. It requires all waveforms to be available, so it needs to be run before they are dropped, i.e. during Stage0.
The algorithm was already in `icaruscode` (and PR #525 is moving it to `icarusalg`). It is described in [`icarus::PMTWaveformBaselinesFromChannelData` class documentation](https://icarus-exp.fnal.gov/at_work/software/doc/icaruscode/latest/classicarus_1_1PMTWaveformBaselinesFromChannelData.html).
This pull request queues the execution of this algorithm in `Stage0` (Run 2 only).
Unfortunately it's not a fast algorithm, but the 0.2 second/event it adds do not significantly impact the 100 s/event overall …
> PMT baseline estimation added to Stage0

- icaruscode/Decode/DecoderTools/TriggerDecoderV2_tool.cc
- icaruscode/Decode/DecoderTools/TriggerDecoderV3_tool.cc
Three ICARUS trigger decoder tools have the same class name.
While this is not a problem as long as only one of their libraries is loaded at a time (which is currently the case although it does not have to be in the future), this causes confusioni in the [automatic documentation rendering](https://icarus-exp.fnal.gov/at_work/software/doc/icaruscode/latest/classdaq_1_1TriggerDecoder.html) by Doxygen.
These changes modify the class names of two of the tools, and should have no other observable consequence.
A sibling request #532 covers the production branch.
> Renamed trigger decoder tool classes

- fcl/caf/cafmakerjob_icarus.fcl
This feature was introduced in https://github.com/SBNSoftware/icaruscode/pull/384 to [release/SBN2022A](https://github.com/SBNSoftware/icaruscode/tree/release/SBN2022A), but never been propagated to develop branch. This is to incorporate with the intrinsic "shift" in CRT simhit timimgs; They all starts from "0", but those zeros represents -1.6ms before the beam gate. I put two references where this value is defined.
> Setting CRTSimT0Offset to 1.6ms in MC CAFMaker

- fcl/configurations/database_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_icarus_mc.fcl
- fcl/reco/Stage0/Run2/stage0_run2_raw_icarus.fcl
- fcl/reco/Stage1/Run2/stage1_run2_icarus_MC.fcl
- fcl/reco/Stage1/Run2/stage1_run2_nofilter_icarus.fcl
- fcl/reco/Stage1/Run2/stage1_run2_wc_icarus_MC.fcl
- fcl/services/calibrationservices_icarus.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/CMakeLists.txt
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROIWavelets_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/roiTools_icarus.fcl
At the ICARUS Analysis Meeting of 3/9/23 it was agree that we would run the stage 0 processing without the 2D deconvolutuion and so this has been removed from the stage0 fhicl files. Note that for MC production we should use "stage0_run2_icarus_mc.fcl". 
In addition, in order to reduce the memory footprint, the stage 1 files have been modified to remove the "SelectEvents" qualifier for root output. For stage 1 the file for MC should be "stage1_run2_icarus_MC.fcl". 
This PR also introduces a fhicl definition file for using the database to recover channel status information. Currently the default usage is unchanged from previous, but this allows upgrading in the near future. 
Finally, there is also the introduction of a tool for using wavelets to do ROI finding. This code is unused but will …
> fhicl file updates as agree at Analysis meeting of 3/9/23

- icaruscode/TPC/Calorimetry/NormalizeDriftSQLite_tool.cc
- icaruscode/TPC/Calorimetry/NormalizeYZSQL_tool.cc
I propose here three optimisations to speed up the normalising tools used in `GnocchiCalorimetry` module (copy setup data only once per event, avoid data structure copies, use faster lookup algorithm).
One of the three optimisations requires an interface change, which is the subject of pull request LArSoft/larreco#54 to `larana`.
The bottlenecks have been identified with ForgeTools Map profiler.
Overall in my test I observe a conspicuous speedup (larger than ×20), with an event being processed in 0.15" (compared to 5" before the changes). This makes a big difference in a workflow I am running.
I haven't provided a branch for production. If this is needed, a patch release of `larreco` will also be needed, unless we give up the optimisation that requires it or a different approach is used …
> Speed optimisation for `GnocchiCalorimetry` tools

- fcl/configurations/database_icarus.fcl
- fcl/g4/intime_g4_icarus.fcl
- fcl/gen/corsika/prodcorsika_proton_intime_icarus_bnb.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/recowire_icarus.fcl
- icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
- test/ci/icarus_ci_intimecosmic_reco1_quick_test_icaruscode.fcl
- test/ci/icarus_ci_nucosmics_reco1_quick_test_icaruscode.fcl
- test/ci/icarus_ci_single_reco1_quick_test_icaruscode.fcl
- ups/product_deps
This includes some last minute updates:
1. Add some protection in space point building to try to avoid program termination when accessing the channel status DB
2. Switch to channel status DB version v1r1 which has matching channel lists for the two tables it currently contains
3. Update the CI test reco1 fhicl files to use the run 2 stage 1 fhicl files
4. Update the intime g4 fhicl file to include modules needed for ML work
Note that this needs icarus_data v09_70_00 to pick up the updated channel status DB and will need the new release of sbncode to get a fix to make sure the MCParticleLite works correctly.
> Last bits for the release?

- fcl/g4/intime_g4_icarus.fcl
- fcl/g4/standard_g4_icarus.fcl
- fcl/gen/corsika/prodcorsika_proton_intime_icarus_bnb.fcl
- fcl/reco/CMakeLists.txt
- fcl/reco/Definitions/stage0_icarus_defs_run1.fcl
- fcl/reco/Definitions/stage1_icarus_defs.fcl
- fcl/reco/Stage0/Run1/stage0_run1_crtpmtfilter_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_crtpmtfilter_icarus.fcl
- fcl/reco/Stage1/Run2/stage1_run2_icarus.fcl
- fcl/reco/Stage1/Run2/stage1_run2_icarus_MC.fcl
- fcl/reco/larcv/CMakeLists.txt
- fcl/reco/larcv/Run2/CMakeLists.txt
- fcl/reco/larcv/Run2/larcv_icarus.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/recowire_icarus.fcl
A few fhicl file fixes:
1) Remove the leading/trailing bins from the ROI finding to address apparent issues with pandora track/shower id
2) Add explicit fhicl files running the CRT PMT filter at stage 0 for both run 1 and run 2
3) Raise the message level in the stage 1 fhicl files from "DEBUG" to "INFO"
4) Kill the warning level messages at the g4 stage from SimDriftElectrons and McReco when it can't find a wire corresponding to a position, not sure if this is a real problem that we need to track down but so far it seems more an annoyance than a bug
5) Fix the intime generation file to insure the MCParticleLite collection is stored
> Various fhicl file fixes to production release

- fcl/caf/cafmaker_add_detsim2d_icarus.fcl
- fcl/caf/cafmakerjob_icarus_detsim2d.fcl
- fcl/caf/cafmakerjob_icarus_detsim2d_noevtwgt.fcl
- fcl/caf/cafmakerjob_icarus_detsim2d_systtools_and_fluxwgt.fcl
New cafmaker fcl based on existing detsim2d cafmaker fcl, but without running systtools or fluxweight. The event weights fail to run on intime cosmic MC so this is needed to make those CAFs.
> CAFmaker w/o event weights for detsim2d

- fcl/reco/Definitions/stage1_icarus_defs.fcl
- fcl/reco/Stage1/Run2/trigger_eff_stage1_icarus.fcl
- icaruscode/Analysis/trigger/ArtObjects/CMakeLists.txt
- icaruscode/Analysis/trigger/ArtObjects/TrackTreeStoreObj.h
- icaruscode/Analysis/trigger/ArtObjects/classes.h
- icaruscode/Analysis/trigger/ArtObjects/classes_def.xml
- icaruscode/Analysis/trigger/BeamGateInfoFromTracksCRT_module.cc
- icaruscode/Analysis/trigger/CMakeLists.txt
- icaruscode/Analysis/trigger/Objects/TrackTreeStoreObj.h
- icaruscode/Analysis/trigger/Objects/classes_def.xml
- icaruscode/Analysis/trigger/TimeTrackTreeStorageCRT_module.cc
- icaruscode/Analysis/trigger/TimeTrackTreeStorage_module.cc
- icaruscode/Analysis/trigger/TimedTrackSelectorCRT_module.cc
- icaruscode/Analysis/trigger/createtree_timed_tracks_icarus_CRT.fcl
- icaruscode/Analysis/trigger/details/CathodeCrossingUtils.cxx
- icaruscode/Analysis/trigger/select_timed_tracks_CRT_icarus.fcl
- icaruscode/CRT/CRTUtils/crtt0matchingalg_icarus.fcl
- icaruscode/CRT/crtt0producer_icarus.fcl
- icaruscode/TPC/Calorimetry/NormalizeYZSQL_tool.cc
- icaruscode/Utilities/ArtAssociationCaches.h
- icaruscode/Utilities/ComparisonHelpers.h
This PR encompasses the updates discussed in the trigger meeting on the trigger efficiency. Most of the changes are restricted to a separate directory used for the trigger efficiency analysis directly but the main change relevant for the collaboration as a whole is a stage1 fcl file that runs the CRTT0Matching module separately for both the west and east cryostats and creates a separate data product based on those. At the moment this is a standalone fcl file that can be run separately. 
One thing I recall is that some of these changes are tied to a larreco change, https://github.com/LArSoft/larreco/pull/54 (@PetrilloAtWork am I correct?) and https://github.com/SBNSoftware/icaruscode/pull/543 so we need to know whether that is compatible I have it working in my own area thanks to Gianluca …
> Processing for trigger efficiency and related changes to trigger efficiency analysis

- icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx
- icaruscode/PMT/Algorithms/PMTsimulationAlg.h
- icaruscode/PMT/Algorithms/pmtsimulation_icarus.fcl
@Temigo  (and possibly another person who right now I don't remember, for which I apologise) has reported an issue which was tracked down to the following.
The PMT digitisation creates PMT waveforms out of simulated photoelectrons. It utilises a form of zero suppression driven by a discrimination algorithm (which has not much to do with the one used in the CAEN V1730B readout boards). Whenever the algorithm determines a "trigger primitive",  a buffer is filled around it and stored.
The discrimination algorithm was written to issue a trigger primitive every time the signal moves from below a threshold to above a threshold. Unfortunately this algorithm was paired with a 4 µs buffer length. In this situation, a strong signal which stays above threshold longer than 4 µs will have its tail …
> PMT digitization does not truncate large signals any more.

- icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
In looking into an issue seen in the MC reconstruction and in leaving no stone unturned discovered that a fraction of space points built by the cluster 3D space point code could be considered redundant. This is because its possible to have space points made from only 2 hits, one each from 2 planes. This defines a point in space with the YZ coordinates defined by the "intersection" point of the two wires containing the hits. If you add a third hit then the YZ position is slightly altered but this small change is well within the voxel dimensions used by the ML people and doesn't matter in the pandora processing. A redundant point can be created when you try to use a 2 hit combination more than once... so include here some protection that prevents that from happening.
At this time making …
> Update to 3D space point building to reduce overall volume of space point output

- fcl/reco/Definitions/stage0_icarus_driver_common.fcl
- fcl/reco/Definitions/stage1_icarus_driver_common.fcl
- fcl/reco/Stage0/Run2/stage0_run2_savewires_icarus_mc.fcl
- fcl/reco/Stage1/Run1/stage1_multiTPC_icarus_gauss.fcl
- fcl/reco/Stage1/Run1/stage1_multiTPC_icarus_gauss_MC.fcl
- fcl/reco/Stage1/Run1/stage1_multiTPC_nofilter_icarus_gauss.fcl
- fcl/reco/Stage1/Run1/stage1_singleTPC_nofilter_icarus_gauss.fcl
- fcl/reco/Stage1/Run2/stage1_run2_icarus.fcl
- fcl/reco/Stage1/Run2/stage1_run2_icarus_MC.fcl
- icaruscode/Decode/MCDecoderICARUSTPCwROI_module.cc
- icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
Updating the run 1 and run 2 reco fhicl files to better manage the messages that are output to log files as the jobs run. Two primary issues, first is the potential volume of messages which was due to "DEBUG" level settings (unfortunately, left over from testing), the other was that at stage 1 there was suppression of all messages except those explicitly asked for. Hopefully we achieve a compromise here where we can get WARNING level (and above) messages for some number of events then suppression after. As a bonus we have recovered the job summary at the end of stage 1 (which is handy when running interactively). 
There is also a formatting change for the MC decoder which is purely aesthetics.
> Last of the fhicl file updates

- fcl/gen/text/prodtext_standard_icarus.fcl
Commit LArSoft/larsim#85 added a mandatory parameter `Offset` to `TextFileGen` module, a breaking change which ICARUS codebase did not absorb.
This is the belated fix.
Thanks to Hector Carranza (whose GitHub user I can't find) for reporting this issue.
Suggested reviewers:
* @SFBayLaser, workflow overlord
* The Real Ndrej, because of retaliation
> `prodtext_standard_icarus.fcl`: add mandatory parameter

- icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx
The algorithm creating readout buffers (future `raw::OpDetWaveform`) from the continuous readout was written expecting (and asserting) that a trigger primitive can't be at the first tick of the enable gate. This was a reasonable assumption when the trigger algorithm looked for a transition from the previous tick from below to above threshold. Now an alternative algorithm is also available which considers just the value of the sample compared to the threshold, so that expectation is violated and the assertion failed. A small change in the algorithm makes it robust to that rare occurrence.
Thanks to @gputnam for the perfect report (code version, input file, input configuration, error message). As a punishment, he gets to review the change.
> Fix a bug in PMT digitization

- icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx
This is the request twin of #568, but for `develop` instead of the production branch.
All discussion should go there.
> Fix a bug in PMT digitization [`develop`]

- fcl/gen/mevprtl/CMakeLists.txt
- fcl/gen/mevprtl/alp/CMakeLists.txt
- fcl/gen/mevprtl/alp/alp_corsika_p_gen_icarus.fcl
- fcl/gen/mevprtl/alp/alp_em_gen_icarus.fcl
- fcl/gen/mevprtl/alp/alp_em_tree_icarus.fcl
- fcl/gen/mevprtl/alp/alp_gen_icarus.fcl
- fcl/gen/mevprtl/alp/alp_gen_icarus_M300.fcl
- fcl/gen/mevprtl/alp/alp_gen_icarus_M500.fcl
- fcl/gen/mevprtl/alp/alp_gen_icarus_M600.fcl
- fcl/gen/mevprtl/alp/alp_gen_icarus_M700.fcl
- fcl/gen/mevprtl/alp/alp_tree_icarus.fcl
- fcl/gen/mevprtl/alp/alp_tree_icarus_M300.fcl
- fcl/gen/mevprtl/alp/alp_tree_icarus_M500.fcl
- fcl/gen/mevprtl/alp/alp_tree_icarus_M600.fcl
- fcl/gen/mevprtl/alp/alp_tree_icarus_M700.fcl
- fcl/gen/mevprtl/hnl/hnl_tau_tree_icarus.fcl
Depends on https://github.com/SBNSoftware/sbncode/pull/339.
This PR provides configurations to generate ALP and HNL decaysin ICARUS MC enabled by the corresponding update to sbncode.
NOTE: this is not needed for the upcoming MCP. It is intended to be merged once the corresponding sbncode PR is merged.
> Generation Configurations for ALP model in ICARUS

- fcl/reco/Stage0/RunA/stage0_runA_icarus_triggerV1.fcl
The standard Run1 (and Run2) Stage0 configuration utilizes the signal on some of the spare channels of PMT readout boards to align the PMT waveforms with the global trigger.
That assumes that those channels have the digitised global trigger signal, which has been the case since Run1 included and a bit earlier.
Some runs though do not have it for sure, including runs `7924` and `7926`, popular since they were eye-scanned for neutrino interactions. Those runs have a different signal in the channel, a trigger primitive signal which if used for the correction creates issues like a multi-peaked waveform time (and downstream flash time) distribution.
This pull request removes such correction from the decoding stage.
Unfortunately there are no staged data files that I know of between `7926` and …
> Don't apply PMT correction on old data where it's not available

- fcl/detsim/commissioning/triggersim_icarus_data.fcl
- icaruscode/PMT/Trigger/SlidingWindowTriggerSimulation_module.cc
The affected module is used to run trigger emulation and create `raw::Trigger` data products out of them, and to create plots at the same time. It's not the module used for the global trigger simulation.
It used to crash, with this fix it does not any more. The bug does not affect the simulation, just the plots.
That's pretty much it.
Not sure if it needs a review...
> Fix a bug in `SlidingWindowTriggerSimulation`

- icaruscode/CRT/CRTPMTMatchingProducer_module.cc
- icaruscode/CRT/CRTUtils/CRTPMTMatchingUtils.cxx
- icaruscode/CRT/CRTUtils/CRTPMTMatchingUtils.h
- icaruscode/CRT/crtpmtmatchingproducer_icarus.fcl
- icaruscode/IcarusObj/CRTPMTMatching.h
- icaruscode/Utilities/DumpCRTPMTMatching_module.cc
This pull request is meant to address the suggestions by @francescopoppi on the candidate version of the CRT/PMT matching producer:
* flash ID should be added
* matches should be sorted by flash time
Both require some choices, which I am explaining here.
The `icarus::crt::CRTPMTMatching` object is ready to host as data member the ID of the flash that is being matched.
Unfortunately, `recob::OpFlash` is one of the data products which do not have an ID field.
On top of that, creating one is not trivial since the flashes live in ICARUS in two independent data products, one per cryostat. Given the absence of a native ID, the only reliable way to assign a flash an ID is to extract its value from the fields of the flash itself; otherwise, given a flash ID, there is no way to figure out to which …
> Add flash ID to CRT/PMT matching and sorting them by flash time

- icaruscode/CRT/CRTPMTMatchingAna_module.cc
There was a bug where a vector of time differences between flashes and CRT hits was not cleared.
> Correction of a bug where a vector was not cleared.

- fcl/reco/Stage0/RunA/stage0_runA_icarus_triggerV1.fcl
Recent changes have introduced in Stage0 the PMT/CRT matching algorithm as a (noop) filter.
The current implementation of the algorithm requires input about trigger configuration.
The "RunA" configurations are based on the live Run2 configurations, so they are fated to include all the changes applied to the latter. The CRT/PMT matching one is a change that RunA can't support for lack of input information (trigger configuration started being saved in data just a bit earlier than Run1 start).
This request removes the CRT/PMT matching specifically for RunA Stage0 processing. It is possible to change the algorithm not to need that information (the work being done right now on the _producer_ side of the matching already does it), but this is not the content of this PR which just removes the …
> Removed CRT/PMT matching from stage0_runA_icarus_triggerV1.fcl

- icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
This somehow snuck into another PR (even after reverted) and into a tagged release... sigh...
> Reverts a commit of snippet3DHitBuilder which is on a feature branch and not ready for prime time

- fcl/reco/Definitions/stage0_icarus_defs.fcl
- fcl/reco/Definitions/stage0_icarus_defs_run1.fcl
- fcl/reco/Definitions/stage0_icarus_driver_common.fcl
- fcl/reco/Definitions/stage0_icarus_driver_common_run1.fcl
- fcl/reco/Definitions/stage1_icarus_defs.fcl
- fcl/reco/Definitions/stage1_icarus_driver_common.fcl
- fcl/reco/Stage0/Run1/stage0_run1_icarus.fcl
- fcl/reco/Stage0/Run1/stage0_run1_icarus_lite.fcl
- fcl/reco/Stage0/Run1/stage0_run1_icarus_mc.fcl
- fcl/reco/Stage0/Run1/stage0_run1_raw_icarus.fcl
- fcl/reco/Stage0/Run1/stage0_run1_raw_icarus_lite.fcl
- fcl/reco/Stage0/Run1/stage0_run1_rawpmt_icarus.fcl
- fcl/reco/Stage0/Run1/stage0_run1_wc_icarus.fcl
- fcl/reco/Stage0/Run1/stage0_run1_wc_icarus_lite.fcl
- icaruscode/Analysis/trigger/magic_raw_to_triggeremu_icarus_Run1_data.fcl
- icaruscode/Filters/CMakeLists.txt
- icaruscode/Filters/FilterDataIntegrity_module.cc
- icaruscode/Filters/icarus_FilterDataIntegrity.fcl
- icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
I've picked out the commits to those two PR's and created PR against release/SBN2023A
> Copy of PR #590 and PR 591 for production branch

- fcl/caf/cafmakerjob_icarus.fcl
This PR disables the parameter used to convert OpFlash times saved in CAFs from trigger reference time to beam gate reference time for MC cafmakerjobs. This shift was only ever meant to be applied to data, as MC uses beam gate reference time anyway. Before trigger emulation was introduced, it did not matter that the shift was also applied to MC because it was just adding `0`. Now that there is a meaningful trigger time in our simulation, it is necessary to turn this off. 
_For CAFs already produced with trigger emulation and without this PR_, one can still recover the real time of each flash by subtracting off the value `triggerinfo.trigger_within_gate`.
> Set ReferencePMTFromTriggerToBeam to false for MC CAFs

- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
When the configuration requests not to save any waveform (or maybe just the standard PMT waveforms), the decoder module would not declare them to _art_, but then it would attempt to put them into the _art_ event anyway, which _art_ did not like at all.
Fixed now removing the attempt to put the waveforms in the event in that condition.
Not a big deal, no hurry.
Tested with `stage0_run2_icarus.fcl` (verified that the waveforms are still saved) and with a special version of `decodePMT_icarus.fcl` with no waveform saving (verified that the commit fixes the issue).
No idea whom could review this... @mvicenzi? @SFBayLaser :black_joker:?
A twin PR #598 takes care of the production branch.
> Fix to PMT decoder bug

- icaruscode/Decode/DecoderTools/TriggerDecoderV3_tool.cc
The assertion ensured that bits that were assumed unused were indeed not used. The addition of adder information on some of those bits invalidated the check.
Reviewers: @jzettle is enjoying his rest and this is urgent, so it goes to run coordination and trigger expert.
> Removed trigger decoder V3 assertion

- fcl/services/simulationservices_icarus.fcl
This PR simply copies the `QAlpha` parameter as listed here:
https://github.com/LArSoft/larsim/blob/3e844a9349adfc27dd7ce8ac5141ff3eae764c67/larsim/Simulation/simulationservices.fcl#L59C14-L59C14
It would be better for ICARUS to refer to the parameters from the LArSoft `simulationservices.fcl` file through the `@local::` command than to just explicitly copy each parameter.
> Provide now-required QAlpha parameter

- icaruscode/Utilities/ArtHandleTrackerManager.h
It was reported a segmentation fault from a module using `ArtHandleTrackerManager`. It turns out that the input of that module was defective and the handle being created was invalid, which `ArtHandleTrackerManager::getHandle()` could handle not.
Now it handles that scenario by not attempting to track an invalid handle and returning the invalid handle to the caller, similarly to the `art::Event::getHandle()` call that it is wrapping.
So that job will still fail, but with a meaningful error.
This is a bug fix of not very critical importance.
PR #616 is the twin change for production branch.
> ArtHandleTrackerManager can now handle invalid handles

- icaruscode/Analysis/crtpmtmatching_parameters.fcl
Fix value saved in GlobalT0Offset, an additional time delay to be applied to the CRT-PMT distribution for MC only. This change was already made on develop branch and got missed for a production release.
> fix time offset for CRT-PMT time difference in MC (production)

- fcl/reco/Definitions/decoderdefs_icarus.fcl
- fcl/reco/Definitions/stage0_icarus_defs.fcl
- fcl/reco/Definitions/stage0_icarus_mc_defs.fcl
- icaruscode/PMT/CMakeLists.txt
- icaruscode/PMT/CopyBeamTimePMTwaveforms_module.cc
- icaruscode/PMT/SimPMTIcarus_module.cc
The `CopyBeamTimePMTwaveforms` is used for size reduction of data samples.
It makes a copy of selected PMT waveforms, only if they contain a time point.
In production, that point is chosen to be the time of opening of the beam gate. This effectively forces the preservation of a waveform that extends from -7 to +19 µs from the beam gate front.
For a potential future use in MC samples, we would like the coverage to be similar.
This module could not guarantee that, since the duration of the waveform around the beam gate is shorter.
This pull request changes the module to accept a time interval instead of a single time point, and it will copy all the waveforms that overlap with that time interval. In this way it is guaranteed that no information is lost (there may still be gaps in that …
> CopyBeamTimePMTwaveforms module to support MC

- icaruscode/Decode/ChannelMapping/ChannelMapPostGres_tool.cc
- icaruscode/Decode/ChannelMapping/ChannelMapSQLite_tool.cc
- icaruscode/Decode/ChannelMapping/RunPeriods.h
- icaruscode/Decode/ChannelMapping/channelmapping_icarus.fcl
- icaruscode/Decode/DecoderTools/TriggerDecoderV3_tool.cc
- ups/product_deps
This is an almost-twin PR of #623: that was for production branch, this is for develop.
The code is the same (:cherries:) with just an adjacent-change conflict resolved.
*But* in order to make any sense, `develop` code must also need to be able to _decode_ the new runs with the new mapping, which is the reason I have also put in this PR the workaround on the trigger decoder at PR #605, which had not been proposed for `develop` yet.
Reviewers: mostly @mvicenzi, because he's going to use this branch anyway to verify that mapping.
It is reasonable, but not absolutely necessary, for this PR to wait until his checks are completed (anyway these changes are already in the _production_ branch...).
> Updated PMT channel mapping (20230829) [develop]

- fcl/reco/Definitions/stage0_icarus_defs_run1.fcl
- fcl/reco/Stage0/Run1/stage0_run1_icarus.fcl
A bug was found where the Stage0 definitions for Run1 did not include CRTPMTMatching Producer module.
This PR fixes the issues. I ask @PetrilloAtWork for his reviews, to understands if there are other items missing from the Stage0 definitions for Run1 which are on the other hand present in Stage0 definitions for Run2.
This is a PR for a production patch!
> Run1 Stage0 Definitions update

- icaruscode/Timing/CMakeLists.txt
- icaruscode/Timing/PMTTimingCorrectionsProvider.cxx
- icaruscode/Timing/PMTTimingCorrectionsProvider.h
- icaruscode/Timing/timing_corrections_tags.fcl
- icaruscode/Timing/timing_icarus.fcl
This is twin PR of #614 meant for production.
It contains two things:
- Switch to using local database for PMT time corrections 
- Introduction of cosmics corrections. These can be disabled by setting the fcl parameter `CorrectCosmics` (from `icaruscode/Timing/timing_icarus.fcl`) to `false`.
Cosmics corrections require `icarus_data` 09_77_00 or newer, which should already be satisfied in the latest production patches.
> PMT timing corrections from local db + Run 1 cosmics corrections [SBN2023A]

- icaruscode/Timing/timing_corrections_tags.fcl
- icaruscode/Timing/timing_icarus.fcl
Twin PR of #626 
- Laser corrections now cover the entire Run 2 period.
- A null table is added so that cosmics corrections for Run 1 are NOT applied to Run 2 data.
(The `icarus_data` v09_79_01 requirement is already satisfied by production since the last patch release)
> Update laser calibration tags for run2 [SBN2023A]

- icaruscode/Timing/PMTTimingCorrectionsProvider.cxx
- icaruscode/Timing/PMTTimingCorrectionsProvider.h
- icaruscode/Timing/timing_corrections_tags.fcl
- icaruscode/Timing/timing_icarus.fcl
This PR updates the tags of the timing calibration databases (`v2r0` -> `v2r1`) to pick up the latest PMT laser corrections for Run 2. This is also necessary for the extractions of the next-level corrections for Run 2, as cosmics corrections are computed on top of the laser ones.
**Note**: This update depends on new `pmt_cable_delays_data.db` and `pmt_laser_timing_data.db` files, which should be packaged in a concurrent `icarus_data` release. These files have been produced by @jedori0228 and tested by both of us.
Asking reviews from people that are (willingly or not) involved in this business.
> Update laser calibration tags for run2

- fcl/reco/Definitions/stage0_icarus_defs_run1.fcl
- fcl/reco/Stage0/Run1/stage0_run1_icarus.fcl
A bug was found where the Stage0 definitions for Run1 did not include CRTPMTMatching Producer module.
This PR fixes the issues. I ask @PetrilloAtWork for his reviews, to understands if there are other items missing from the Stage0 definitions for Run1 which are on the other hand present in Stage0 definitions for Run2.
This is a PR for develop release
> This updates the Run1 definitions for develop.

- icaruscode/Decode/ChannelMapping/ChannelMapPostGres_tool.cc
As [promised](https://github.com/SBNSoftware/icaruscode/pull/620#issuecomment-1690226045) to @SFBayLaser in #622 , this PR updates `PostGresChannelMap_tool` to handle the time-period awareness now required by the PMT channel mapping. 
The FNAL DB team has changed the structure of the `pmt_placements` table, adding a timestamp (`period_active`) which can be used to select the time period. Since the database itself was changed, this is a breaking change: the old software is no longer able to read the PMT table correctly. However, it is important to note that PostGres is no longer actively used, and it is kept only as a backup option.
To read off the new table structure:
- The query for the database was changed, appending a SQL `where` clause: `"&w=period_active:eq:"+fCurrentPMTTimestamp`
- …
> Update PostGres tool for new PMT mapping

- icaruscode/CRT/CRTDataAnalysis_module.cc
This PR includes a new feature to the CRT Hit calibration ntuple.
Originally only the sum of the PEs in one CRT Hit was stored in the HitTree. This PR includes 3 new branches (arrays of size 32) to the HitTree.
1st Branch is PEs, for the Top CRT (for which all the 32 channels of the FEB are recorded) each index of the PEs array correspond to the channel of the FEB, the entry is the corresponding calibrated PE value. The Side CRTs only store information of the channels that are actively part of the reconstructed CRT Hit, this is due to how the Side CRT works (multiple channels from different FEB participate in a hit). For the Side CRT you loose correspondance between channel and index, this is nonetheless fixed with the inclusion of a 2nd branch (array): Chans.
2nd Branch is Chans: for the …
> Update to the CRT calibration Ntuple

- icaruscode/TPC/ICARUSWireCell/wcls-decode-to-sig-base.fcl
- icaruscode/TPC/SignalProcessing/HitFinder/CMakeLists.txt
- icaruscode/TPC/SignalProcessing/HitFinder/HitConverter_module.cc
- icaruscode/TPC/SignalProcessing/HitFinder/hitfindermodules_icarus.fcl
The first breaks the 2D deconvolution so need this fix as patch.
Second will allow studies by others of test gauss hit finder which uses ChannelROIs as input.
> Quick fix of typo in configuration file + module to convert icarus::Hits to recob::Hits

- icaruscode/CRT/CRTPMTMatchingAna_module.cc
Previously there was the requirment for a certain number of opHits to be above threshold to consider the flash valid. The bug did not initialze some vectors when the nopHitAboveThreshold was lower then the requirments. Since in the future threshold will change, I removed the strong skipping-the-flash condition and I added the number of opHits above threhsold as a variabile for the analyzers to cut on.  This PR was previously approved by reviewe.
> This commit fixes a bug in the CRT-PMT matching analyzer module. 

- icaruscode/Analysis/trigger/TimeTrackTreeStorageCRT_module.cc
- icaruscode/Analysis/trigger/TimeTrackTreeStorage_module.cc
- icaruscode/Analysis/trigger/createtree_timed_tracks_icarus.fcl
- icaruscode/Analysis/trigger/magic_raw_to_triggeremu_icarus_Run1_data.fcl
One-line change to trigger efficiency modules to extract the hit-level dE/dx information from the standard calorimetry modules in the NTuples used for the trigger efficiency analyses instead of a homebrew function in the module. Tested extensively that the production works and values are output using the production branch v09_72_00_05p04 by Riccardo Triozzi and shown to work. Can test again directly with this version if requested by review.
> Change trigger efficiency NTuple hit-level dE/dx information to output of standard calorimetry modules

- fcl/detsim/detsim_2d_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_icarus_keepup.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_icarus_mc.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_raw_icarus_mc.fcl
- icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
These fhicl files are meant to be used for reprocessing Run 2 data and for MC simulations. These versions are to start validation and may be updated...
> Updated 2d simulation/deconvolution fhicl files for validation of pending 2024 release

- fcl/configurations/calibration_database_GlobalTags_icarus.fcl
- fcl/configurations/calibration_database_PMT_TagSets_icarus.fcl
This PR updates the PMT calibration database tags to pick up the most recent corrections which should cover the beginning of Run 3. In particular:
- Cable delays are updated given the summer work on the laser system (`v2r4`).
- New laser corrections are included following the replacement of the signal cables and the new gain equalization (`v2r2`).
**Note**: This change requires a concurrent release of `icarus_data` containing the updated database files.
-------
@PetrilloAtWork Addressing here your comment from below: the cosmics-based corrections downstream are computed starting from the laser-correct ophit times and added on top. Assuming they get invalidated if you change the laser corrections is a conservative assumption we make. Comparing actual data, the issue is not as bad as we …
> New tags for Run 3 laser corrections

- icaruscode/TPC/ICARUSWireCell/detsimmodules_wirecell_ICARUS.fcl
The inputs to the Wire Cell model were updated in a recent release of icarus_data. The existing parameter controlling the scale of the coherent noise in `detsimmodules_wirecell_ICARUS.fcl` was not updated to match data, which this PR does. 
Some context: previously, this scale factor was used to scale the coherent noise upwards to match data. This is no longer necessary as the noise model matches data with no fine-tuning of scale factors (all scales set to 1.0).
I have made a small sample with both the default and with the change in this PR and verified that this PR is needed to match the data sample that was used to generate the model. The plot below supports this claim (though it is not very presentable). Note that the average noise levels in data (listed below the plots) are only …
> Fixed the coherent noise scale factor (1.09 -> 1.0) to match data

- fcl/reco/Stage0/Run2/partial/stage0_run2_icarus_opdetonly.fcl
- icaruscode/Decode/DecoderTools/TriggerDecoderV2_tool.cc
- icaruscode/Decode/DecoderTools/TriggerDecoderV3_tool.cc
- icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc
- icaruscode/PMT/Algorithms/CMakeLists.txt
- icaruscode/PMT/Algorithms/OpDetWaveformMetaUtils.h
- icaruscode/PMT/Algorithms/PMTverticalSlicingAlg.cxx
- icaruscode/PMT/Algorithms/PMTverticalSlicingAlg.h
- icaruscode/PMT/CMakeLists.txt
- icaruscode/PMT/CopyBeamTimePMTwaveforms_module.cc
- icaruscode/PMT/PMTWaveformBaselinesFromChannelData_module.cc
- icaruscode/PMT/ReassociatePMTbaselines_module.cc
- icaruscode/PMT/RequireOnBeamWaveforms_module.cc
- icaruscode/PMT/Trigger/Algorithms/SlidingWindowPatternAlg.cxx
- icaruscode/PMT/Trigger/Algorithms/TriggerGateBuilder.cxx
- icaruscode/PMT/Trigger/Algorithms/TriggerGateBuilder.h
- icaruscode/PMT/Trigger/CMakeLists.txt
- icaruscode/PMT/Trigger/DiscriminatedAdderSignal_module.cc
- icaruscode/PMT/Trigger/LVDSgates_module.cc
- icaruscode/PMT/Trigger/SlidingWindowTrigger_module.cc
- icaruscode/PMT/Trigger/TriggerSimulationOnGates_module.cc
- icaruscode/PMT/Trigger/Utilities/TriggerDataUtils.h
- icaruscode/PMT/Trigger/Utilities/TriggerGateDataFormatting.h
- icaruscode/PMT/Trigger/dump_triggergatedata_icarus.fcl
- icaruscode/PMT/Trigger/run_addertriggersimulation_icarus_data.fcl
- icaruscode/PMT/Trigger/trigger_emulation_icarus.fcl
- icaruscode/PMT/Trigger/trigger_icarus.fcl
- icaruscode/Utilities/IcarusObjectSelectors.h
- scripts/runFilesFromSAM.sh
- scripts/sortDataLoggerFiles.py
This extensive pull request includes several updates and bug fixes for trigger emulation support.
Highlights:
1. Support for emulation on `Stage0` files: the information available for on-beam trigger emulation is fragmented: a module copies out the subset of the PMT waveforms that includes the beam gate; but some information associate to the original waveforms are not reassociated to the new ones. This PR introduces both some fixes and some mitigation for the existing data.
2. Support for adder bit decoding: the decoder relies on a convention to store adder bits into new `sbn::ExtraTriggerInfo` data members introduced in SBNSoftware/sbnobj#96.
3. New software to simulate the adder boards, the discrimination of their signal and the trigger logics.
One fix that is not included is in the …
> Large trigger code update: adder emulation, updates to pair-based trigger emulation

- icaruscode/TPC/Tracking/ICARUSPandora/scripts/PandoraSettings_Neutrino_ICARUS.xml
This PR contains the new training for track vs shower discrimination in Pandora automatic reconstruction (i.e. LArBdtPfoCharacterisation) based on ICARUS bnb simulations (icaruscode v09_72_01) and including three new BDT variables.
This PR should also include changes to branches with the same name of the following repositories:
- feature/acampani_sdellepi_new_BdtPfoCharacterisation in sbnanaobj
- feature/acampani_sdellepi_new_BdtPfoCharacterisation in sbncode 
- the new BDT training .xml file  in icarus_data/icarus_data/PandoraMVAs/PandoraBdt_v09_72_01_ICARUS_pfochar_bnb.xml
> New training based on bnb ICARUS simulations for track vs shower discrimination 

- fcl/detsim/detsim_2d_icarus_refactored.fcl
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-refactored.jsonnet
This PR adds a new jsonnet file for the new refactored g4. The jsonnet file is identical to the standard one except for the input label to the wclsDepoFluxWriter, which is set to 'ionization'. The fcl file is updated consequently. This is needed to be able to test the new G4 in larger scale productions.
> add wcls jsonnet for refactored g4

- icaruscode/PMT/Algorithms/pmtsimulation_icarus.fcl
- icaruscode/PMT/OpReco/fcl/icarus_spe.fcl
The set of new parameters attempts to mitigate the discrepancy of reconstructed optical hit amplitude between data and simulation. Details can be found in [https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=34640](SBN DocDB 34640) and previous presentations; the parameters are taken from the "MC6" test therein.
The new set of parameters include:
1. PMT effective quantum efficiency: 7.3% (previously 12.1%)
2. PMT gain 7.5·10⁶ (previously 9.7·10⁶)
3. digitisation "zero suppression" threshold 15 ADC# (previously 18 ADC#)
The new parameters are set into a configuration set labelled `202401patch`, while the old configuration set has gained the label `202202`. The `202401patch` set is chosen as standard for ICARUS processing.
This PR is coupled with, and requires, …
> Optical detector simulation and reconstruction parameter tests [2/2]

- fcl/g4/dirts_bnb_g4_sce_on.fcl
- fcl/gen/genie/dirt_icarus_bnb.fcl
- fcl/gen/genie/dirt_icarus_bnb_sce_on.fcl
- icaruscode/Filters/CMakeLists.txt
- icaruscode/Filters/FilterDirts.fcl
- icaruscode/Filters/FilterDirts_module.cc
I added here few things that can be used to produce dirt events for the BNB beam! The code I must confess is not so "beautiful" but I commit it in any case to try to have it for the new release! In particular there are :
- a couple of fhicl files in fcl/gen/genie to generate the dirts events
- a filter module and its fhicl to remove the neutrino interactions with the vertex inside the active volume or that did not deposit energy in the detector
> materials for the simulation of dirts BNB events added

- fcl/caf/cafmakerjob_icarus.fcl
- icaruscode/CRT/CRTUtils/CRTHitRecoAlg.cc
- icaruscode/CRT/CRTUtils/CRTHitRecoAlg.h
- icaruscode/CRT/crthitproducer.fcl
- icaruscode/CRT/crtsimhitproducer.fcl
This pull request applies fGlobalT0Offset, a fhicl parameter that should be applied to simulated CRT Hit times only, to the CRTHitProducer. This offset gets [added to the true time in the CRTDetSimAlg](https://github.com/SBNSoftware/icaruscode/blob/develop/icaruscode/CRT/CRTUtils/CRTDetSimAlg.cc#L616) before passing the true time to a timestamp generator. This offset should be subtracted back off so the simulated CRT Hit distribution is centered around 0, ranging from -1.5 ms to +1.5 ms. 
This offset is currently applied to the simulated CRT Hit times in the CAFs and the CRT-PMT Matching producer, but is not applied to _all_ simulated CRT hit times (for ex., this offset is missing in calibration ntuples). This is a flaw in the workflow; we should have this offset applied as high up in the …
> apply offset to simulated CRT Hit times as the CRT Hits are being produced

- fcl/reco/Stage1/Run1/stage1_multiTPC_icarus_gauss_alltracks_ntuple.fcl
- fcl/reco/Stage1/Run2/stage1_run2_icarus_alltracks_ntuple.fcl
This PR is intended to include two new FCL files in the Stage1 reconstructions which allow to store all the tracks in the Calibration Ntuple and not only the CC ones.
> Storing all tracks in Calibration Ntuple

- fcl/reco/Stage0/Run1/stage0_run1_icarus.fcl
- fcl/reco/Stage0/Run1/stage0_run1_raw_icarus.fcl
- fcl/reco/Stage0/Run1/stage0_run1_rawpmt_icarus.fcl
- fcl/reco/Stage0/Run1/stage0_run1_wc_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_icarus_crtpmtonly.fcl
- fcl/reco/Stage0/Run2/stage0_run2_raw_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_crtpmtfilter_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_raw_icarus.fcl
This PR adds the drop of the artdaq::Fragments produced by the new compression algorithm (icarus_produce_compressed_job.fcl) to all the stage0 fcl files that were previously dropping DAQ data.
> drop the new compressed fragments

- fcl/configurations/calibration_database_GlobalTags_icarus.fcl
- fcl/configurations/calibration_database_TPC_TagSets_icarus.fcl
Add and update TPC channel status db tag in TagSets and also update GlobalTag. `icarus_data` `v09_83_01` already contains this new tag.
> Update TPC Channel Status database tags to v3r2

- icaruscode/TPC/Calorimetry/NormalizeTPCSQL_tool.cc
- icaruscode/TPC/Calorimetry/NormalizeYZSQL_tool.cc
- icaruscode/TPC/Calorimetry/normtools_icarus.fcl
- We are passing time stamp to TPC dqdx and YZ calibration DB querying; drift correction module was correctly using run number. 
- Using SQL db as default for TPC calibration
> Use run number for TPC calibration

- icaruscode/TPC/ICARUSWireCell/icarus/simparams.jsonnet
This PR updates the `drift_speed` within `icaruscode/TPC/ICARUSWireCell/icarus/simparams.jsonnet` to reflect measurements by @gputnam (see [SBN-doc-23346-v1](https://sbn-docdb.fnal.gov/cgi-bin/sso/RetrieveFile?docid=23346&filename=driftV.pdf&version=1)).
See also [icarusalg PR #81](https://github.com/SBNSoftware/icarusalg/pull/81)
Here, I am using a value based on the measurement for the West cryostat. Since I don't believe the drift speed can be set for each cryostat independently, would it be better to choose a value somewhere between the two measured drift speeds of each cryostat?
> Update the drift velocity in the WireCell simparams.jsonnet

- fcl/reco/Stage0/Run2/partial/decodeTrigger_icarus.fcl
- icaruscode/Decode/ChannelMapping/ChannelMapDumper.cxx
- icaruscode/Decode/ChannelMapping/ChannelMapPostGres.cxx
- icaruscode/Decode/ChannelMapping/ChannelMapPostGres.h
- icaruscode/Decode/ChannelMapping/ChannelMapSQLite.cxx
- icaruscode/Decode/ChannelMapping/ICARUSChannelMapDataTypes.h
- icaruscode/Decode/ChannelMapping/ICARUSChannelMapProviderBase.h
- icaruscode/Decode/ChannelMapping/ICARUSChannelMapProviderBase.tcc
- icaruscode/Decode/ChannelMapping/IChannelMapping.h
- icaruscode/Decode/ChannelMapping/IICARUSChannelMap.h
- icaruscode/Decode/ChannelMapping/IICARUSChannelMapProvider.h
- icaruscode/Decode/ChannelMapping/channelmapping_icarus.fcl
- icaruscode/Decode/DecoderTools/CMakeLists.txt
- icaruscode/Decode/DecoderTools/TriggerDecoderV3_tool.cc
- icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.cxx
- icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.h
- icaruscode/TPC/Compression/producecompressedjob.fcl
- icaruscode/Utilities/CacheCounter.h
- icaruscode/Utilities/Expected.h
This pull request includes two parts:
1. an extension of the channel mapping service to provide additional PMT information on PMT pair and adder signals and their path through the hardware; this also includes an utility to extract that mapping information in a format convenient for higher level usage.
2. a trigger decoder able to process and extract all the additional information carried by the adder triggers, including which trigger logic caused the acquisition (majority, adders or both) and the trigger primitive bits that were active at the time of the trigger.
These changes need to be supported by a new channel mapping database with the additional information; with the existing database, the code will still work but won't unpack the trigger primitive bits correctly (close to it, but …
> Trigger decoder for adder triggers

- fcl/g4/larg4_icarus.fcl
- fcl/g4/larg4_icarus_intime.fcl
- fcl/g4/larg4_services_icarus.fcl
- fcl/g4/mergesimsources_icarus.fcl
- fcl/gen/corsika/prodcorsika_proton_intime_filter_bnb.fcl
These additions to the refactored LArG4 fcls to enable the creation of data products needed by the ML reconstruction chain. This is a mimic of a similar SBND PR by @bear-is-asleep. 
The ML team has validated that this truth information is sufficient. 
This relies on a number of other PRs across a number of packages:
SBNCode: https://github.com/SBNSoftware/sbncode/pull/430
LArG4: https://github.com/LArSoft/larg4/pull/52
LArSim: https://github.com/LArSoft/larsim/pull/131
> Workflow to enable ML File Production with refactored LArG4

- icaruscode/TPC/Compression/icarus_produce_compressed_job.fcl
This PR adds the data integrity filter to the recompression fcl. This is needed to avoid failures for files where some events have corrupted daq information.
> add data integrity filter to recompression fcl

- fcl/reco/Stage0/Run2/stage0_run2_wc_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_icarus_keepup.fcl
- icaruscode/Analysis/tools/TrackHitEfficiencyAnalysis_tool.cc
- icaruscode/Analysis/tools/analysis_tools_icarus.fcl
- icaruscode/TPC/ICARUSWireCell/detsimmodules_wirecell_ICARUS.fcl
- icaruscode/TPC/ICARUSWireCell/icarus/sp.jsonnet
1) A bug was reported in the keepup processing fhicl file that caused a loss of purity monitor output. This was because the input RawDigit data product names were wrong, set back to default.
1) Adjusted the interplane time offsets and the overall deconvolution offset (in the finall inverse FFT) to get simulation and reconstruction times to match for truth matching.
> Two updates: bug fix for keep up processing, adjust interplane time offsets and decon timing for truth matching

- fcl/reco/Stage0/Run2/partial/decodePMT_icarus_treeonly.fcl
- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
With the new adder-based trigger, the PMT diagnostic tree should know whether the light collected at beam gate was coming from an adder or a majority trigger.
This commit adds that information to the tree, one piece of information per cryostat, directly from the trigger information.
_Edit_: it also adds a count of triggers from the beginning of the run and the gates from the previous trigger. This tree is being used for trigger studies as well.
_And_ a job configuration to create such trees, for the benefit of grid jobs.
Reviewer: @mvicenzi as PMT decoder insider.
> Added trigger logic information to PMT decoder diagnostic ROOT tree

- fcl/configurations/rootoutput_icarus.fcl
I am adding a preset of `RootOutput` module for having one output file per input file.
This can be handy when there is room for having jobs processing multiple input files but for which a one-to-one correspondence between input and output file is desired.
I also recommend the production workflows to explicitly use this one, although it's not my decision to take.
Reviewers:
* @SFBayLaser: ICARUS workflow manager
> rootoutput_icarus.fcl: added icarus_rootoutput_one_output_per_input

- icaruscode/Decode/ChannelMapping/ChannelMapPostGres.cxx
This is a follow up from #720. The hardware PostGres DB was updated in RITM2043469, and new data has been added to the existing tables. Due to some internal constraints, column names are required to be lowercase so I'm updating the hardcoded names in `ChannelMapPostGres.cxx` to match them.
This was tested with `ChannelMapDumper`, and confirmed to be working.
> Update PostGres DB new column names

- icaruscode/PMT/Algorithms/pmtsimulation_icarus.fcl
This is a minor fix to the PMT simulation configuration.
Some noise tool configurations were not correctly referenced but rather bypassed.
And one of the bypass had an obsolete tool name (so the configuration without electronics noise was effectively broken).
I have verified that `detsim_1d_icarus.fcl` in `develop` and on this branch come out the same (i.e. this is just an internal fix).
Reviewers: two people more or less informed on ICARUS PMT simulation.
> Internal fix to PMT simulation configuration

- fcl/g4/intime_g4_icarus.fcl
- fcl/g4/larg4_icarus.fcl
- fcl/g4/larg4_icarus_intime.fcl
This PR fixes a few issues with G4 fcl that were not detected in time for v09_88_00_02.
1. Usage of legacy G4 was not fixed in intime_g4_icarus.fcl
2. Revert some mcreco changes that are not ready yet (may be changed back with next larsim and after tests from ML group)
3. Wrong output module used in larg4_icarus_intime.fcl
> fix a few issues with g4 fcl files

- fcl/g4/larg4_icarus.fcl
- fcl/g4/larg4_icarus_intime.fcl
- fcl/g4/mergesimsources_icarus.fcl
- fcl/g4/simplemerge_icarus.fcl
- fcl/gen/corsika/prodcorsika_proton_intime_filter_bnb.fcl
- fcl/reco/Definitions/stage1_icarus_defs.fcl
- fcl/reco/Stage1/Run2/stage1_run2_1d_larcv_icarus_Cosmic.fcl
- fcl/reco/Stage1/Run2/stage1_run2_larcv_icarus_Cosmic.fcl
- stage1_run2_larcv_icarus_Cosmic.fcl, stage1_run2_1d_larcv_icarus_Cosmic.fcl, added for intime cosmic larcv generation. 
- larg4_icarus.fcl / larg4_icarus_intime.fcl updated
- mergesimsources_icarus.fcl / simplemerge_icarus.fcl  trackId offset added
> ML refactoring compatible with larsim version for larsoft v09_89

- fcl/g4/larg4_icarus.fcl
- fcl/syst_variations/refactored_g4_icarus_step1.fcl
- fcl/syst_variations/refactored_g4_icarus_step2.fcl
- fcl/syst_variations/refactored_g4_icarus_step2_variations.fcl
- fcl/syst_variations/stage0_variation_icarus_savewires.fcl
This PR is meant to try to fix the issue seen in v09_89_01 with Supera running when attempting to test things for the variation. Also includes small changes needed for ML running in a couple of the variation fcl. This PR supersedes https://github.com/SBNSoftware/icaruscode/pull/733 and was made in coordination with @yeonjaej ensuring I had included the same changes she did in her PR. Making this against develop as that and the v09_89_01 tag are identical according to github.
Still testing this with the neutrino-only samples to make sure the issue is fixed to the level we can quickly. Also notifying @cerati and @SFBayLaser about this. Will comment results of testing over the rest of the night/tomorrow morning and we can discuss how to patch the release if everything is successful. …
> Fix ML chain for ICARUS systematics and standard productions

- doc/icaruscode.doxy
- doc/scripts/updateLocalDocumentation.sh
- doc/scripts/utilities.sh
* LArSoft has moved to a different server, and since we somehow link to their "tag file", we need an update 
* ROOT tag file is now compressed (Gzip), but (my) Doxygen does not support that: the documentation update script now decompresses tag files
* bug fix (it seems Alma Linux 9 Bash is more picky than Scientific Linux 7)
> Updates for Doxygen documentation generation

- scripts/sortDataLoggerFiles.py
**TL;DR:** `sortDataLoggerFiles.py` couldn't detect duplicate files any more. This patch fixes it.
A recent DAQ change in the output file name pattern introduced two numbers (an `art` and a `EventBuilder` index) in place of a single one (data logger, `dl`). To support both formats, the number that used to represent the data logger in `sortDataLoggerFiles.py` was replaced by an object that could represent either a data logger or a builder+thread pair.
This quantity (formerly number, now object) was also directly used as a unique key to identify duplicate files. Python then implicitly used the address of an object as component of that key instead of the value of the number (or of the object). Duplicate files would get different objects (with different addresses) with the same value, which …
> sortDataLoggerFiles.py: fixed duplicate file identification

- fcl/caf/cafmaker_defs.fcl
- fcl/caf/cafmakerjob_icarus_data.fcl
For NuMI backport release. Depends on https://github.com/SBNSoftware/sbncode/pull/439.
> Update to data-based calibration for ICARUS MCS reco

- fcl/gen/mevprtl/higgs/dissonant_higgs_gen.fcl
- icaruscode/TPC/Calorimetry/NormalizeTPCSQL_tool.cc
- icaruscode/TPC/Calorimetry/NormalizeYZSQL_tool.cc
- icaruscode/TPC/Calorimetry/normtools_icarus.fcl
Cherry-picked two commits from #699 to feature/howard_forNuMI2023A_from_gputnam-configs which is one of our working branch for 2023A NuMI project.
> Cherry-picked #699 to feature/howard_forNuMI2023A_from_gputnam-configs

- fcl/caf/cafmaker_defs.fcl
- fcl/caf/cafmakerjob_icarus_data.fcl
- fcl/caf/cafmakerjob_icarus_data_rereco_numi.fcl
- fcl/caf/cafmakerjob_rereco_numi_icarus_systtools_and_fluxwgt.fcl
- fcl/caf/cafmakerjob_rereco_numi_icarus_systtools_and_fluxwgt_ReprocRelease.fcl
- fcl/caf/cafmakerjob_rereco_numi_icarus_systtools_and_fluxwgt_ReprocRelease_stage1.fcl
- icaruscode/CRT/crtpmtmatchingproducer_icarus_numi_Run1_ReprocRelease.fcl
There was a request to adding CRT-PMT matching, FlashMatching, and barycenter FlashMatching back to our reprocessing, for the inclusive muon analysis. This PR includes necessary fhicl updates for that. For our Run1 data inputfiles (stage1), they have crthit objects produced during the `stage1`, so we should not drop them; so made an update in  `source.inputCommands`. It was `MCstage0` stage for the MC, so it's fine.
Also cherry-picked https://github.com/SBNSoftware/icaruscode/pull/739; this is to save GENIE EventRecord as a default MC cafmaker.
> Updating fhicls for 2023A NuMI reproecssing

- fcl/gen/numi/genie_icarus_numioffaxis.fcl
This is a new set of NuMI flux files produced from the `main_modern_g4` branch of G4NuMI. These files include important fixes to the NuMI geometry and physics modeling. Currently, each of the two FHC/RHC directories contain 1000 files x 500k POT, totaling 500M POT. This will be expanded to 2B POT in the near future as soon as the space to accommodate the full production is made available.
This PR resolves the first task outlined in #746.
> Update FluxSearchPaths to point to the latest NuMI flux production

- fcl/g4/larg4_services_icarus.fcl
With this PR we switch to using the QGSP_BERT_HP Geant4 physics list. This is analogous to the sbndcode PR https://github.com/SBNSoftware/sbndcode/pull/468 and is the ICARUS-specific implementation of the goal mentioned in sbncode PR https://github.com/SBNSoftware/sbncode/pull/462 by @marcodeltutto. 
More details in sbncode issue https://github.com/SBNSoftware/sbncode/issues/453
Comparison of performances is below (10 events generated with prodcorsika_bnb_genie_protononly_icarus.fcl followed by larg4_icarus_cosmics_sce_2d_drift.fcl).
Original (SBN_QGSP_BERT_NNC):
```
Hadronic Processes for neutron
Process: hadElastic
Model:             hElasticCHIPS: 0 eV  ---> 100 TeV
Cr_sctns:        G4NeutronElasticXS: 0 eV  ---> 100 TeV
Process: neutronInelastic
Model:                      QGSP: 12 …
```
> Use QGSP_BERT_HP physics list

- fcl/caf/cafmaker_defs.fcl
- fcl/caf/cafmakerjob_icarus_data.fcl
From https://github.com/SBNSoftware/sbncode/pull/459, which is merged to develop, I added a feature to save GENIE event record to the CAFMaker output. Here I set the default value of a boolean, `SaveGENIEEventRecord`, to `true`; this is crucial to constantly adopt new cross-section systematics without re-running CAFMaker job. More importantly, we now stopped updating [LarSoft/nusystematics](https://github.com/larsoft/nusystematics) but moved to [NuSystematics/nusystematics](https://github.com/NuSystematics/nusystematics), and there are some missing dials that we cannot currently evaluate from `lar` based jobs. We can add those once we have GENIE record saved together with StandarRecord.
> Set SaveGENIEEventRecord as true be default cafmaker fcl

- icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx
I just got fed up of reading that wrong information, probably because it was me to write it.
So the photon library does not include any quantum efficiency; the quantum efficiency is applied before writing the scintillation photons (`sim::SimPhotons[Lite]`) in `G4` stage.
Reviewer is who picks the shortest straw... @amenegol.
> Fix wrong comment in PMTsimulationAlg

- icaruscode/TPC/Calorimetry/calorimetryICARUS.fcl
- icaruscode/TPC/Calorimetry/normtools_icarus.fcl
The values shifted slightly in preparation for publication. Now they are official: https://arxiv.org/abs/2407.12969
> Update EMB calibration to published values

- fcl/reco/Stage0/Run2/stage0_run2_rawpmt_icarus.fcl
This requests adds `stage0_run2_rawpmt_icarus.fcl`, a Stage0 job configuration which keeps all PMT waveforms.
It is intended for special runs and for reference runs that people can use for detailed studies (for example, request for Run3 runs `11813` and `11816` is ongoing).
The standard configuration, `run3_stage0_icarus.fcl`, duplicates the PMT waveforms including the trigger time (new data product `daqPMTonbeam`) and then drops the complete PMT data product (`daqPMT`), except for the special PMT waveforms that are stored in their own data products.
The new configuration does not drop, but rather keeps, the `daqPMT` original waveforms.
To reduce the waste, the PMT waveforms from `daqPMTonbeam` are instead dropped (the other data products it produces are instead preserved).
The module …
> stage0_run2_rawpmt_icarus.fcl: Stage0 configuration preserving PMT waveforms

- icaruscode/IcarusObj/classes.h
- icaruscode/IcarusObj/classes_def.xml
- icaruscode/PMT/OpReco/ICARUSFlashAssAna_module.cc
- icaruscode/PMT/OpReco/fcl/icarus_opana_modules.fcl
Last minute fixes for runtime bugs coming from new code of #751 .
Thanks to @aheggest for spotting them!
* Added missing dictionary definitions for the new `PMTBeamSignal` structure.
* Disabled waveform ouput tree from `ICARUSFlashAssAna` in stage1 (no optical waveforms available).
* Removed useless debug flag (does nothing, goes nowhere)
> Run-time bug fixes for PR#751

- icaruscode/CRT/CRTPMTMatchingAna_module.cc
- icaruscode/CRT/CRTPMTMatchingProducer_module.cc
- icaruscode/CRT/CRTUtils/CRTPMTMatchingUtils.cxx
This Commit fixes a bug that we found in the CRT PMT Matching produce…. The classification was evaluated on the wrong flash time (it used the first op hit peak time as a reference. This is wrong, one could think of using the first op hit start time, but definetly not the first op hit peak time. Using the flash time is also ok, and the important thing is that this is now consistent with the evaluation of the CRT-PMT time differences.
> Bug fix to CRT PMT Matching producer

- icaruscode/Decode/ChannelMapping/Legacy/ChannelMapPostGres_tool.cc
- icaruscode/Decode/ChannelMapping/Legacy/ChannelMapSQLite_tool.cc
- icaruscode/PMT/Algorithms/ParsingToolkit.h
- icaruscode/PMT/Calibration/CaloTools/SPEChargeLogisticResponse.h
- icaruscode/PMT/OpReco/ICARUSBeamStructureAna_module.cc
- icaruscode/PMT/OpReco/ICARUSFlashAssAna_module.cc
- icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.h
Clang 14 (`c14:prof`) complains about a few lines of code.
While the merit of the complains is arguable (not plain wrong, nor right), "fixing" the code is cheap, and needed if we want to compile with Clang.
The fixes are simple and technical.
Reviewers: who is the Collaboration C++ expert?
> Fixes from Clang compilation errors

- icaruscode/CRT/CRTPMTMatchingAna_module.cc
- icaruscode/CRT/CRTPMTMatchingProducer_module.cc
- icaruscode/CRT/CRTUtils/CRTPMTMatchingUtils.cxx
The flashClassification was based on the first Optical Hit Peak time, but the time differences stored in the data product were evaluated wrt the flash time. Flash time is the correct variable to be used. This fix is already included in develop release.
> This fixed a CRTPMTMatchingProducer bug.

- fcl/caf/cafmaker_defs.fcl
- fcl/caf/cafmakerjob_icarus_data.fcl
This is a copy of https://github.com/SBNSoftware/icaruscode/pull/739.
Setting `SaveGENIEEventRecord` to `true` for default `MC` CAFMaker, and then set it to false for `data` CAFMaker.
This PR requires https://github.com/SBNSoftware/sbncode/pull/478.
> Set SaveGENIEEventRecord as true be default cafmaker fcl [release/SBN2024A]

- fcl/syst_variations/detsim_2d_filter.fcl
- icaruscode/TPC/ICARUSWireCell/detsimmodules_wirecell_ICARUS.fcl
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-refactored-filtersed.jsonnet
A request that this PR is really geared towards a patch release of icaruscode v09_89_01_01p03 for ICARUS systematics. We can include it here for continued functionality in develop, but I need a patch release (github doesn't let me do it or I am not git-savvy enough to have found it quickly). With the other changes here I do not want this currently merged into develop while we figure out more broadly how to include the other pieces of this
Description
Please provide a detailed description of the changes this pull request introduces. If available, also link to a docdb link where the issue/change have been presented on/discussed.
This pull request introduces a larsoft module that can be run during the detsim stage to filter out SimEnergyDeposits around a rectangular volume and creates a new …
> Implementing SimEnergyDeposit Filter for z = 0 in the production release

- fcl/syst_variations/cafmakerjob_icarus_variation_lifetimehi.fcl
- fcl/syst_variations/cafmakerjob_icarus_variation_lifetimelow.fcl
- fcl/syst_variations/scrub_stage1_nuonly_variations_icarus.fcl
This is really a pull request for v09_89_01_01p03 so I think this is the right branch.
This adds the changes in the CAF making to enable to full electron lifetime variation sample. The previous samples did not adjust the lifetime in the reconstruction, only in the simulation which causes an exaggeration of the effect. This PR corrects that and adds the ability to make this adjustment in the reconstruction too.
> Committing CAFmaker changes needed for full electron lifetime variations

- icaruscode/CRT/CRTPMTMatchingProducer_module.cc
As discussed here: https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=39068
There was one more issue which needed to be addressed in the CRTPMT matching data product.
The requirement of a specific number of opHits to be above threshold does have some reasoning behind and it is a good way to reject fake flashes, but this is a decision that the analyzers should do, not the data product.
I just comment this part because for our current production we can survive with skipping this requirement.
I probably will follow with opening an issue about the addition of the number of op hit above threshold in the data product (sbnobj) and in the Standard Record (sbnanaobj). At that point I will address this once again in the CRTPMTMatching Producer.
> Removal of the requirement of a certain number of opHit to be above a given threshold

- fcl/syst_variations/cafmakerjob_icarus_detsim2d_nosimchan.fcl
- fcl/syst_variations/detsim_2d_icarus_refactored_yzsim_nomerge.fcl
- fcl/syst_variations/stage0_run2_icarus_mc_refactored_nosimchan.fcl
- fcl/syst_variations/stage1_variation_icarus_larcv_nosimchan.fcl
- fcl/syst_variations/supera_icarus_MC_all_cryo_PMT_CRT_nosimchan.fcl
This adds the fcls needed for the YZ Production (since it does not currently support SimChannel). 
This is the workflow needed for the YZ Production:
```
detsim_2d_icarus_refactored_yzsim_nomerge.fcl
stage0_run2_icarus_mc_refactored_nosimchan.fcl 
stage1_variation_icarus_larcv_nosimchan.fcl 
cafmakerjob_icarus_detsim2d_nosimchan.fcl 
```
> Adding fcls for YZ systematic production

- icaruscode/CRT/CRTPMTMatchingProducer_module.cc
This was introduced in icaruscode v09_89_01_02 and in develop.
It should remain in develop, the reason for return to the old version is that it could change selection w.r.t. CV evaluated on icaruscode v09_89_01_01p03.
> This PR reverts the requirement of opFlash with op hits following trigger like requirements. 

- fcl/gen/numi/genie_icarus_numioffaxis.fcl
I have updated the search paths for Genie to locate the flux files, from version v03_00 to v03_0, redirecting them to the most recent set.
> Updating NUMI flux files from v3_00 to v3_01 [release/SBN2024A]

- icaruscode/CRT/CRTPMTMatchingProducer_module.cc
This was introduced in icaruscode v09_89_01_02 and in develop.
It should remain in develop, the reason for return to the old version is that it could change selection w.r.t. CV evaluated on icaruscode v09_89_01_01p03.
> This PR reverts the requirement of opFlash with op hits following trigger like requirements.

- fcl/syst_variations/detsim_2d_icarus_refactored_variation_signalstretch_down.fcl
- fcl/syst_variations/detsim_2d_icarus_refactored_variation_signalstretch_up.fcl
These fcls allow us to stretch or shrink the electronic response shape. 
More details and validation can be found in this DocDB:
https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=39697
> Signal Shape Systematic Fcls

- fcl/caf/cafmakerjob_icarus_cosmic_detsim2d.fcl
Currently, if you try to use CAF Maker on cosmic MC, it breaks because it tries to build the GENIE record. 
The simplest solution is to add a new CAF maker fcl that disables the GENIE Event Record storage. 
This is needed by the CI
> Adding CAF Fcl for for Cosmics

- icaruscode/TPC/ICARUSWireCell/detsimmodules_wirecell_ICARUS_YZsim.fcl
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-yzsim-refactored.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-yzsim-shifted-refactored.jsonnet
This PR enables us to use the correct YZ maps (which are on a icarus_data branch called `feature/jzennamo_v3_yzmaps`), fixes a bug in the response function numbering, and corrects an issue with configuring the cathode flatness.
> Fixing Bad YZ Maps 

- icaruscode/Overlays/CMakeLists.txt
Should have been included in https://github.com/SBNSoftware/icaruscode/pull/817. Also can be superseded by https://github.com/SBNSoftware/icaruscode/pull/813.
> Get Overlay code to compile

- icaruscode/Decode/DecoderTools/TriggerDecoderV3_tool.cc
Changes in the trigger information conveyed via DAQ fragments are documented in [SBN DocDB 36264](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=36264) and link therein.
The new information needs to be extracted and stored into a data product (see SBNSoftware/sbnobj#110 for the data product extension).
These changes enable the ICARUS trigger decoder tool V3 to decode the new format of data (whose version number is by chance also `3`).
The changes all pertain the cryostat-specific information about global trigger candidates in that cryostat; this information lands on a `sbn::ExtraTriggerInfo::CryostatInfo` object. The information of each cryostat is treated independently from the other. The changes are the following:
* LVDS bits (including the adders'), the cryostat trigger …
> Trigger decoder update to unpack the new trigger diagnostics
