SBNSoftware/icaruscode

- icaruscode/TPC/Simulation/SpaceCharge/SpaceChargeICARUS.cxx
TPC 0s needed an extra negative sign.
> fixed negative SCE x-shift bug

- fcl/reco/reco_icarus.fcl
Need this feature branch to move from TRACS to pandora for showers (officially)
> Uncomment the Pandora Shower stuff and used for a test.

- fcl/gen/corsika/prodcorsika_proton_intime_icarus_bnb.fcl
> Change gen-in-time filter to enforce particles only arriving in beam tim

- doc/icaruscode.doxy
- doc/scripts/experiment_settings.sh
- doc/scripts/settings.sh
- doc/scripts/updateLocalDocumentation.sh
Not clear how well, yet they do.
> Doxygen generation scripts now support multiple repositories

- fcl/reco/reco_icarus.fcl
- icaruscode/TPC/Calorimetry/calorimetryICARUS.fcl
- icaruscode/TPC/Calorimetry/calotest_icarus.fcl
Making a pull request, as it needs to be included for SBN 2020A.
> calorimetry included in reco2 with current develop

- icaruscode/Decode/DecoderTools/decodertools.fcl
Small updates for signal processing which should give some small improvements for processing
> Updates for signal processing 

- fcl/g4/Purity/g4_enable_spacecharge_1ms.fcl
This is a request by @mrmooney for the PAC and ICARUS commissioning
> Adding 1ms fcl for commissioning

- icaruscode/PMT/Algorithms/AsymExpPulseFunction.h
No consequence (well, except that now it will run also in debug mode).
> Fixed incorrect assert() in single photoelectron response code.

- icaruscode/Decode/stage0_icarus_defs.fcl
- icaruscode/Decode/stage0_single_icarus.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
Updates the module for finding ROIs and modifies the fhicl to run everything (1D, 2D, ROI finding, etc.)
> Decoder updates 

- fcl/gen/corsika/prodcorsika_proton_intime_icarus_bnb.fcl
- fcl/gen/corsika/prodcorsika_proton_intime_icarus_numi.fcl
A clone of Gray Putnam's work for BNB.
Documentation is in the top of the FHiCL file itself.
> Added job for cosmic ray simulation in time with NuMI beam gate

- fcl/detsim/CMakeLists.txt
- fcl/detsim/commissioning/CMakeLists.txt
- fcl/detsim/commissioning/run4642like_detsim_icarus.fcl
- fcl/detsim/commissioning/run4759like_detsim_icarus.fcl
- fcl/detsim/commissioning/triggersim_singlewindow_icarus.fcl
- fcl/detsim/commissioning/triggersim_singlewindow_icarus_data.fcl
- fcl/detsim/standard_opdetsim_icarus.fcl
- fcl/gen/corsika/commissioning/CMakeLists.txt
- fcl/gen/corsika/commissioning/prodcorsika_300us_icarus.fcl
- fcl/gen/genie/CMakeLists.txt
- fcl/gen/genie/commissioning/CMakeLists.txt
- fcl/gen/genie/commissioning/simulation_genie_background_icarus_bnbJan2020_300us.fcl
- fcl/gen/genie/commissioning/simulation_genie_background_icarus_bnbJan2020_300us_background.fcl
- fcl/gen/genie/commissioning/simulation_genie_background_icarus_bnbJan2020_300us_signal.fcl
- fcl/utilities/dump_opdetwaveforms_icarus_data.fcl
- icaruscode/PMT/Algorithms/pmtsimulation_icarus.fcl
- icaruscode/PMT/Trigger/LVDSgates_module.cc
- icaruscode/PMT/Trigger/MajorityTriggerEfficiencyPlots_module.cc
- icaruscode/PMT/Trigger/SlidingWindowTriggerEfficiencyPlots_module.cc
- icaruscode/PMT/Trigger/TriggerEfficiencyPlotsBase.cxx
- icaruscode/PMT/Trigger/TriggerEfficiencyPlotsBase.h
- icaruscode/PMT/opdetsim_pmt_icarus.fcl
This also requires pull request SBNSoftware/icarusalg#17.
> Updates to trigger simulation and its configuration.

- icaruscode/Filters/FilterNeutrinosActiveVolume_module.cc
Normally one would directly ask GENIE to generate events with a subset of particle ID (e.g. only ±12, electron neutrinos).
But that has the side effect of killing the pile up (i.e. there will be no event with one electron neutrino interaction _and in addition_ one muon neutrino interaction).
The new addition to this filter module allows this, at the cost of generation efficiency (e.g. only ~6% of NuMI neutrino interactions are from electron neutrinos, so to produce 6 of them 100 events needs to be generated first).
> Added a neutrino ID filter to FilterNeutrinosActiveVolume module

- icaruscode/Filters/CMakeLists.txt
- icaruscode/Filters/FilterNeutrinosActiveVolume_module.cc
Reverts SBNSoftware/icaruscode#126
> Revert "Added a neutrino ID filter to FilterNeutrinosActiveVolume module"

- fcl/gen/CMakeLists.txt
- fcl/gen/text/CMakeLists.txt
- fcl/gen/text/prodtext_standard_icarus.fcl
Adding a configuration that can be used as a base to import events in HEP text format into LArSoft with ICARUS geometry.
> Added template configuration for importing events from a text file.

- doc/scripts/experiment_settings.sh
- doc/scripts/updateLocalDocumentation.sh
This should enable parsing of the correct version of `sbnobj` and others when running `updateLocalDocumentation.sh`.
> Find versions from UPS when building Doxygen documentation

- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DecoderTools/IDecoder.h
- icaruscode/Decode/DecoderTools/PMTDecoder_tool.cc
The PMT configuration extraction feature was removed from the tool.
> Fix to icaruscode issue #133.

- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
The `ROIFinder` module code uses a _copy_ of the full deconvolved waveform to extract the regions of interest.
The existing code used to make all the copies at once and then process the wires plane by plane (possibly in parallel).
This modification delays the copy to just before the processing of a wire plane starts, at which point only the wires in that plane are copied.
This results in a sizeable memory saving when working serially plane by plane, gain which reduces as more planes are processed at the same time (multi-threading).
The modification is still thread-safe since it uses `const` data structures from `art::Event` as input and does not add any storage structure.
At least in theory: I have not tested it multi-threaded. Testing in single thread worked decently well, barred the …
> ROIFinder unrolls wire data lazily.

- icaruscode/Decode/DecoderTools/TPCDecoderFilter1D_tool.cc
- icaruscode/Decode/DecoderTools/TPCDecoderFilter2D_tool.cc
- icaruscode/Decode/DecoderTools/TPCDecoderOverlayFilter1D_tool.cc
- icaruscode/Decode/DecoderTools/TPCDecoderOverlayFilter2D_tool.cc
- icaruscode/Decode/fcl/stage1_multiTPC_icarus_gauss.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/CMakeLists.txt
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/CMakeLists.txt
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/IROILocator.h
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROICannyEdgeDetection_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROIMorphological2D_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/roiTools_icarus.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/recowire_icarus.fcl
This updates the 2D ROI finding scheme to reflect updates in the icarus_signal_processing page. At this time there are not changes observed to the "normal" processing... this will be the starting point for improvements to come in next few weeks.
> Updates to ROI finding phase I

- fcl/services/simulationservices_icarus.fcl
Among other things, brings in parameters for LArQL: https://cdcvs.fnal.gov/redmine/projects/larsoft/wiki/LArQL_algorithm
> Update LArG4Parameters to keep pace with LArSoft

- fcl/reco/reco_icarus.fcl
- fcl/reco/reco_icarus_driver_reco_multitpc_gauss_calonoSCE.fcl
no-SCE calorimetry standalone fcl and corresponding changes to reco_icarus.fcl (as requested by Minerba Bruce et al.)
I may refine this in the future, integrating into reco stage
> no-SCE calorimetry

- icaruscode/Decode/DecoderTools/TPCDecoderFilter1D_tool.cc
- icaruscode/Decode/DecoderTools/TPCDecoderFilter2D_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/IROILocator.h
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROICannyEdgeDetection_tool.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROIMorphological2D_tool.cc
Updates for some changes in icarus_signal_processing
> Signal processing updates

- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROICannyEdgeDetection_tool.cc
- ups/product_deps
This branch contains improvments to the icaruscode tools which access the Canny Edge Detection tools in icarus_signal_processing
> Continuing work on the Canny Edge Detection tools

- icaruscode/Decode/DaqDecoderICARUSTPCwROI_module.cc
- icaruscode/Decode/DecoderTools/TPCDecoderFilter1D_tool.cc
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/Decode/fcl/stage1_icarus_defs.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROICannyEdgeDetection_tool.cc
More updates for decoding, including first attempt at ROI decoder module
> ROI decoder 

- scripts/runFilesFromSAM.sh
Just a small feature of little importance.
> runFilesFromSAM.sh: added option to limit the list length

- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/Filters/run_flashfilter_data.fcl
Updates from Andrea Scarpelli for the flash filter configuration
> Flash updates

- icaruscode/Decode/DaqDecoderICARUSTrigger_module.cc
- icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc
- icaruscode/Decode/DecoderTools/decodertools.fcl
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
- icaruscode/Decode/fcl/test_trigger_decode.fcl
This introduces a trigger decoder which can be inserted into the job flow
> Introducing trigger decoder from Jacob's feature branch

- icaruscode/Decode/BeamBits.h
- icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc
- icaruscode/Decode/fcl/decodePMT_icarus.fcl
- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
this merges in the updates Gianluca made (which I only realized after the initial PR of Jacob's stuff - sorry!).
> Merging in Gianluca's updates to trigger decoder

- icaruscode/Decode/DecoderTools/CMakeLists.txt
- icaruscode/Decode/DecoderTools/Dumpers/CMakeLists.txt
- icaruscode/Decode/DecoderTools/Dumpers/FragmentDumper.cxx
- icaruscode/Decode/DecoderTools/Dumpers/FragmentDumper.h
- icaruscode/Decode/DecoderTools/PMTDecoder_tool.cc
- icaruscode/Decode/fcl/CAEN_V1730_setup_icarus.fcl
- icaruscode/Decode/fcl/decodePMT_icarus.fcl
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
Changes include:
* updated PMT readout board trigger delays
* trigger information in the optional debugging tree output
* in fact, access to the trigger time
Of all this, almost nothing is relevant for multi-window PMT readout.
> Several changes to PMT decoder and decoding

- icaruscode/Decode/CMakeLists.txt
- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DaqDecoderICARUSPMTnotThatOld_module.cc
- icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.cxx
- icaruscode/Decode/DecoderTools/details/PMTDecoderUtils.cxx
- icaruscode/Decode/DecoderTools/details/PMTDecoderUtils.h
- icaruscode/Decode/fcl/decodePMT_icarus.fcl
- icaruscode/Decode/fcl/decodePMT_icarus_incomplete.fcl
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
This decoder has been tested on runs `5974` and `5977`.
The correctness of the waveform timestamps has not been investigated, but at this point chances are that any major problem with timing is in the hardware setup anyway.
> PMT decoder supporting multi-window PMT readout

- icaruscode/Decode/fcl/CAEN_V1730_setup_icarus.fcl
- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/Decode/fcl/stage0_icarus_driver_common.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_splitstream_icarus.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_splitstream_nofilter_icarus.fcl
- icaruscode/Filters/TriggerTypeFilter_module.cc
This sets up to add a third output stream for "unknown" which may not be in place just yet but trying to be ready. In addition there are two general running cases: a) single window PMT readout where we want to run the PMT filter, b) multiple window PMT readout where the PMT filter does not work.
> Updates to handle three output streams and single vs multiple window PMT running. 

- icaruscode/PMT/scripts/MergePhotonLibrary.C
- icaruscode/PMT/scripts/RecompressROOTtrees.C
- icaruscode/PMT/scripts/neoSmazza202012.sh
Improvements from 20210426 campaign, but still the settings of 20201209.
> Updated photon library scripts

- fcl/detsim/wirecell_multitpc_detsim_icarus.fcl
Add a standard fhicl for the 2D field simulation
> multiple tpc simulation with 2d field response

- icaruscode/Decode/fcl/stage1_icarus_defs.fcl
- icaruscode/Decode/fcl/stage1_multiTPC_icarus_gauss.fcl
Depends on https://github.com/SBNSoftware/sbncode/pull/128.
> Add track calorimetry skimming into stage1 processing.

- fcl/g4/overburden/g4_enable_spacecharge_cosmics_ovb.fcl
- fcl/g4/overburden/intime_g4_icarus_sce_on_ovb.fcl
- fcl/gen/corsika/overburden/prodcorsika_proton_intime_icarus_bnb_sce_on_ovb.fcl
- fcl/gen/genie/overburden/prodcorsika_genie_overburden_icarus_Jun2021.fcl
I prepare these fhicls for new productions we would like to do for Event Selection studies. They use the default geomtry with the overburden. Once the new most recent geometry will be committed, these fhicls will be tested again, eventually updated and then used for productions
> fhicls for June 2021 Event Selection productions

- icaruscode/Decode/fcl/stage1_icarus_defs.fcl
- icaruscode/Decode/fcl/stage1_multiTPC_icarus_gauss.fcl
Fixes more stuff in https://github.com/SBNSoftware/icaruscode/pull/189. Depends on SBNSoftware/sbncode#128.
> Run uncalibrated calorimetry for use by the skimmer.

- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_splitstream_icarus.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_splitstream_nofilter_icarus.fcl
- icaruscode/Decode/fcl/stage1_icarus_defs.fcl
- icaruscode/Decode/fcl/stage1_multiTPC_icarus_gauss.fcl
- icaruscode/Decode/fcl/stage1_multiTPC_nofilter_icarus_gauss.fcl
> Moving purity analysis to stage 0, reinstating Gray's calo skimmer

- icaruscode/TPC/Simulation/SpaceCharge/SpaceChargeICARUS.cxx
- icaruscode/TPC/Simulation/SpaceCharge/SpaceChargeICARUS.h
Title. Also resolves https://github.com/SBNSoftware/icaruscode/issues/191.
> Update Space Charge Service in ICARUS to split-wire geometry. Fix typos in coordinate fixing code.

- fcl/gen/CMakeLists.txt
- fcl/gen/mevprtl/CMakeLists.txt
- fcl/gen/mevprtl/higgs/CMakeLists.txt
- fcl/gen/mevprtl/higgs/dissH_M220.fcl
- fcl/gen/mevprtl/higgs/dissH_M260.fcl
- fcl/gen/mevprtl/higgs/dissH_M300.fcl
- fcl/gen/mevprtl/higgs/dissH_M340.fcl
- fcl/gen/mevprtl/higgs/dissonant_higgs_gen.fcl
- fcl/gen/mevprtl/higgs/dissonant_higgs_tree_icarus.fcl
- fcl/gen/mevprtl/hnl/CMakeLists.txt
- fcl/gen/mevprtl/hnl/hnl_M260.fcl
- fcl/gen/mevprtl/hnl/hnl_M280.fcl
- fcl/gen/mevprtl/hnl/hnl_M300.fcl
- fcl/gen/mevprtl/hnl/hnl_M320.fcl
- fcl/gen/mevprtl/hnl/hnl_M340.fcl
- fcl/gen/mevprtl/hnl/hnl_M360.fcl
- fcl/gen/mevprtl/hnl/hnl_M380.fcl
- fcl/gen/mevprtl/hnl/hnl_icarus_gen.fcl
- fcl/gen/mevprtl/hnl/hnl_testray_icarus.fcl
- fcl/gen/mevprtl/hnl/hnl_tree_icarus.fcl
New configurations for MeVPrtl event generation in ICARUS using the NuMI beam.
> Refactor configs and products out of sbncode for MeVPrtl Event Generator

- fcl/configurations/flashmatch_simple_icarus.fcl
- fcl/reco/FlashMatchSimple/fm_scores_icarus.fcl
- fcl/reco/FlashMatchSimple/fm_scores_metrics_icarus.fcl
Depends on https://github.com/SBNSoftware/sbncode/pull/152
Where discussion should happen.
This PR depends on merging branch `feature/icaza/fm_multi` on `icarus_data`, which contains new metrics.
https://cdcvs.fnal.gov/redmine/projects/icarus_data/repository?utf8=✓&rev=feature%2Ficaza_fm_multi
> Simple-Flash Match: multi-matcher, unbiased, tuneable, fast.

- ups/product_deps
Open issue details:
https://github.com/SBNSoftware/sbncode/issues/15#issuecomment-889241974
> move experiment genie_xse dependency to sbncode

- doc/scripts/experiment_settings.sh
- doc/scripts/updateLocalDocumentation.sh
- doc/scripts/utilities.sh
Also, a couple of bug fixes in the documentation scripts.
> Adding sbnanaobj and sbnana in the Doxygen rendering list.

- icaruscode/TPC/SignalProcessing/RawDigitFilter/TPCNoiseMC_module.cc
- icaruscode/TPC/SignalProcessing/RawDigitFilter/TPCNoise_module.cc
- icaruscode/TPC/SignalProcessing/RawDigitFilter/tpcnoise.fcl
- icaruscode/TPC/SignalProcessing/RawDigitFilter/tpcnoiseMC.fcl
- icaruscode/TPC/Simulation/DetSim/detsimmodules_ICARUS.fcl
- icaruscode/TPC/Simulation/DetSim/tools/SBNDataNoise_tool.cc
New noise model based on run 0 data
> Update with new noise model from Filippo Varanini

- fcl/gen/numi/GNuMIFlux.xml
Updated ICARUS position in NuMI coordinates. @betan009 suggested to merge this soon so that the new values can be used in the new MC production.
> Updated ICARUS position based on SBN-doc-22998

- icaruscode/TPC/Tracking/ICARUSPandora/scripts/PandoraSettings_Neutrino_ICARUS.xml
needs to have feature/rh_BDTs from the icarus_data repository incorporated as well
> pointed vertex MVA to new xml file

- icaruscode/Decode/fcl/stage0_singleTPC_onestream_nofilter_icarus.fcl
- icaruscode/Decode/fcl/stage1_singleTPC_nofilter_icarus_gauss.fcl
Requested by Mike Mooney, a stage0 and stage1 set of fhicl files to be able to process older data sets before "multiple TPC" readout or special case readouts
> Include special case fhicl files for stage0 and stage1

- icaruscode/TPC/ICARUSWireCell/convert_Noise_ROOTtoJSON.py
- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/sp.jsonnet
1)Change the wire geometry file to use in 2D simulation
2)Change ADC to mV convertion scaling for signal processing (1400->3300)
> WireCell changes

- icaruscode/TPC/Calorimetry/calorimetryICARUS.fcl
As discussed at the Tuesday Calibration meeting -- update the calorimetry constants in ICARUS MC.
> Update calorimetry constants with comment

- icaruscode/Decode/ChannelMapping/ICARUSChannelMapProvider.cxx
- icaruscode/Decode/ChannelMapping/ICARUSChannelMapProvider.h
This is an implementation of the proposal in icaruscode issue #151.
> Encode PMT channel mapping DB key in the interface to DB

- icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc
- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/Decode/fcl/stage0_icarus_driver_common.fcl
- icaruscode/Decode/fcl/stage0_multiTPC_splitstream_nofilter_icarus.fcl
- icaruscode/Filters/TriggerTypeFilter_module.cc
Added in OffbeamBNB and OffbeamNuMI filter streams/made the rest of the underlying fixes to get the filters to work.
(Also removed single quote deliminators in the trigger decoder tool because my emacs syntax highlighting couldn't handle it and it cost me 30 minutes figuring out that large chunks of code weren't actually commented out/inside quotes. Sorry/not sorry.)
> Update trigger handling for off beam streams

- icaruscode/CRT/CRTUtils/CRTHitRecoAlg.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROIMorphological2D_tool.cc
> Make sure variable is initialized to prevent crashes

- icaruscode/TPC/Calorimetry/calorimetryICARUS.fcl
> Update cal constants for 2021C data processing

- CMakeLists.txt
- icaruscode/Analysis/AnalysisTree_module.cc
- icaruscode/TPC/Simulation/SpaceCharge/SpaceChargeICARUS.cxx
- ups/product_deps
Update versions of Larsoft/icarusalg/icarus_data
> Weekly Release 

- icaruscode/TPC/Simulation/SpaceCharge/SpaceChargeICARUS.cxx
This PR to port Mike Mooney's SCE fix to the production branch. Note that this also needs icarus_data v09_41_00.
> Porting Mike Mooney's fix for space charge to the production branch

- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
> Applying Mike Mooney style fix for wirecell offset

- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
Absolute values of x positions of all anodes/cathodes were decresed by 10cm
> Adopting Mike Mooney's fix for space charge for WireCell

- CMakeLists.txt
- icaruscode/TPC/Simulation/SpaceCharge/SpaceChargeICARUS.cxx
- ups/product_deps
> Production branch backing out SCE fix and moving to v09_37_01_02

- test/ci/ci_tests.cfg
- test/ci/icarus_ci_intimecosmic_detsim_quick_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_detsim_seq_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_g4_quick_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_g4_seq_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_gen_quick_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_gen_seq_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_reco0_quick_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_reco0_seq_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_reco1_quick_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_reco1_seq_test_icaruscode.fcl
Add intime cosmic ci test
Several memory/CPU adjustments
> Intime cosmic CI test

- CMakeLists.txt
- icaruscode/Decode/DecoderTools/CMakeLists.txt
- icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.cxx
- icaruscode/Decode/DecoderTools/PMTconfigurationExtractor.h
- icaruscode/Decode/PMTconfigurationExtraction_module.cc
- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
- icaruscode/Utilities/ReadArtConfiguration.h
- test/ci/ci_tests.cfg
- test/ci/icarus_ci_intimecosmic_detsim_quick_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_detsim_seq_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_g4_quick_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_g4_seq_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_gen_quick_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_gen_seq_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_reco0_quick_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_reco0_seq_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_reco1_quick_test_icaruscode.fcl
- test/ci/icarus_ci_intimecosmic_reco1_seq_test_icaruscode.fcl
- ups/product_deps
> Weekly Release

- icaruscode/TPC/ICARUSWireCell/icarus/params.jsonnet
- ups/product_deps
Updated GARFIELD simulation for WireCell with updated icarus_data dependecy
Prepared for the release patch
> Add Updated GARFIELD simulation

- icaruscode/Analysis/TPCPurityInfoAna_module.cc
- icaruscode/Analysis/TPCPurityMonitor_module.cc
- icaruscode/Analysis/analysis_icarus.fcl
- icaruscode/Decode/DaqDecoderICARUSTPC_module.cc
- icaruscode/Decode/DaqDecoderICARUSTPCwROI_module.cc
- icaruscode/Decode/DecoderTools/CMakeLists.txt
- icaruscode/Decode/DecoderTools/INoiseFilter.h
- icaruscode/Decode/DecoderTools/TPCNoiseFilter1D_tool.cc
- icaruscode/Decode/DecoderTools/TPCNoiseFilterCanny_tool.cc
- icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
- icaruscode/Decode/MCDecoderICARUSTPCwROI_module.cc
- icaruscode/Decode/fcl/decoderdefs_icarus.fcl
- icaruscode/Decode/fcl/stage0_icarus_defs.fcl
- icaruscode/Decode/fcl/stage0_icarus_mc_defs.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/Decon1DROI_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROIFinder_module.cc
This PR should port the necessary updates to the MC decoder to handle the wirecell 2D simulation. Riding along for free is the purity monitor...
> Port decoder updates and purity monitor to production branch

- scripts/runFilesFromSAM.sh
- scripts/sortDataLoggerFiles.py
Support for a stream tag in the name has been added.
> Updated scripts to discover ICARUS data files and sort them.

- icaruscode/Decode/DecoderTools/CMakeLists.txt
- icaruscode/Decode/DecoderTools/details/KeyedCSVparser.cxx
- icaruscode/Decode/DecoderTools/details/KeyedCSVparser.h
- icaruscode/Decode/DecoderTools/triggerPacketParser.cxx
- test/CMakeLists.txt
- test/Decode/CMakeLists.txt
- test/Decode/DecoderTools/CMakeLists.txt
- test/Decode/DecoderTools/KeyedCSVparser_test.cc
An experimental parser for simple key/values CSV﻿ data is updated to support base 16 numbers and string values.
Also added a parser executable to test the parsing of a string.
Unit test and documentation added too.
> Updated CSV parser for trigger packet.

- fcl/detsim/standard_detsim_icarus.fcl
- icaruscode/Analysis/ICARUSPurityDQM_module.cc
- icaruscode/TPC/Utilities/signalservices_icarus.fcl
Christian Farnese has updated the purity monitor code to remove failures due to fitting problems, update the noise scaling factor for the detector simulation as per numbers determined by Justin Mueller.
> This is meant to reconcile TPC related changes on the production branch with the develop branch

- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DecoderTools/details/PMTDecoderUtils.cxx
- icaruscode/Decode/DecoderTools/details/PMTDecoderUtils.h
- icaruscode/Decode/fcl/CAEN_V1730_setup_icarus.fcl
- icaruscode/Decode/fcl/decodePMT_icarus.fcl
This is the twin pull request as #367, but based on `SBN2022A` branch.
See that pull request for details.
> Decode special PMT readout channels (SBN2022A)

- icaruscode/TPC/Tracking/ICARUSPandora/scripts/PandoraSettings_Master_ICARUS.xml
- icaruscode/TPC/Tracking/ICARUSPandora/scripts/PandoraSettings_Master_ICARUS_NuMI.xml
An attempt to use GitHub to recreate https://github.com/SBNSoftware/icaruscode/pull/336 but for the SBN2022A branch.
It didn't seem to flag anything but the simple (desired) XML updates so maybe this is okay?
> Getting the writing of nu id features into the 2022A branch

- icaruscode/TPC/Calorimetry/calorimetryICARUS.fcl
Update the calorimetry constants for the new gain.
> Update calorimetry constants for new TPC gain

- icaruscode/Decode/fcl/stage0_icarus_driver_common.fcl
- icaruscode/Decode/fcl/stage0_run1_icarus.fcl
- icaruscode/Decode/fcl/stage0_run1_icarus_lite.fcl
- icaruscode/Decode/fcl/stage0_run1_raw_icarus.fcl
- icaruscode/Decode/fcl/stage0_run1_raw_icarus_lite.fcl
- icaruscode/Decode/fcl/stage0_run1_rawpmt_icarus.fcl
- icaruscode/Decode/fcl/stage0_run1_wc_icarus.fcl
- icaruscode/Decode/fcl/stage0_run1_wc_icarus_lite.fcl
This is the companion PR to #412
> Create run1 stage0 fhicl files for production branch

- fcl/detsim/wirecell_multitpc_detsim_icarus.fcl
- fcl/detsim/wirecell_multitpc_detsim_icarus_lite.fcl
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-decode-to-sig.jsonnet
- icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel.jsonnet
- icaruscode/TPC/ICARUSWireCell/wcls-decode-to-sig-base.fcl
- icaruscode/TPC/ICARUSWireCell/wcls-multitpc-sim-drift-simchannel.fcl
Introduce a way to configure Field Response input for WireCell simulation through fcl files
PS. Needs to be merged ASAP + icarus_data needs an update with Filed Response files for tests
> Wire Cell Field Response Adjustment

- icaruscode/TPC/Tracking/ICARUSPandora/scripts/PandoraSettings_Neutrino_ICARUS.xml
Marking as draft for now -- I want to make the PRs to do a CI-based test first.
> Set PFO Characterisation BDT to persist features.

- icaruscode/TPC/Calorimetry/CMakeLists.txt
- icaruscode/TPC/Calorimetry/NormalizeDriftSQLite_tool.cc
- icaruscode/TPC/Calorimetry/NormalizeTPCSQL_tool.cc
- icaruscode/TPC/Calorimetry/NormalizeYZSQL_tool.cc
- icaruscode/TPC/Calorimetry/icarus_data_recombination.fcl
- icaruscode/TPC/Calorimetry/normtools_icarus.fcl
Fixes the value, which was mistakenly put to 0.215 in https://github.com/SBNSoftware/icaruscode/pull/428.
> Fix Value of Mod-Box Beta in Calorimetry

- icaruscode/CRT/CRTGeoObjectSorter.cxx
- icaruscode/TPC/SignalProcessing/RecoWire/SimTestPulse/SimTestPulseWire_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/SimTestPulse/SimTestPulse_module.cc
- icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
Pursuant to LArSoft/larcorealg#33
> Accommodate breaking changes in geometry

- fcl/reco/Stage0/Run1/stage0_run1_icarus.fcl
- fcl/reco/Stage0/Run1/stage0_run1_icarus_mc.fcl
- fcl/reco/Stage0/Run1/stage0_run1_rawpmt_icarus.fcl
Rather than fixing each time in my working area, I do it here.
> Fix to Stage0 Run1 configuration output path

- fcl/reco/Definitions/stage0_icarus_defs.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_crtpmtfilter_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_icarus.fcl
- icaruscode/Filters/CMakeLists.txt
- icaruscode/Filters/FilterCRTPMTMatching_module.cc
- icaruscode/Filters/icarus_FilterCRTPMTMatching.fcl
- icaruscode/TPC/SignalProcessing/RecoWire/ROIConverter_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/ROITools/ROIFromDecoder_tool.cc
As the title indicates, have tried to eliminate the extraneous commits inadvertently included with a rogue merge. 
Reference to the original PR #484.
> A "clean" version of PR 484

- fcl/reco/Definitions/decoderdefs_icarus.fcl
- fcl/reco/Definitions/stage0_icarus_defs.fcl
- fcl/reco/Stage0/Run2/partial/decodeTrigger_icarus.fcl
- icaruscode/Decode/DaqDecoderICARUSTrigger_module.cc
- icaruscode/Decode/DataProducts/TriggerConfiguration.cxx
- icaruscode/Decode/DataProducts/TriggerConfiguration.h
- icaruscode/Decode/DataProducts/classes_def.xml
- icaruscode/Decode/DecoderTools/CMakeLists.txt
- icaruscode/Decode/DecoderTools/IDecoder.h
- icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.cxx
- icaruscode/Decode/DecoderTools/TriggerConfigurationExtractor.h
- icaruscode/Decode/DecoderTools/TriggerDecoderDispatcher_tool.cc
- icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
- icaruscode/Decode/TriggerConfigurationExtraction_module.cc
This is the twin pull request of #502; this one targets the release/production branch.
It contains the same three commits as #502: see that PR for details.
> Trigger decoder tool supporting both V2 and V3 data fragment versions [SBN2022B]

- fcl/reco/Definitions/CAEN_V1730_setup_icarus.fcl
This is the twin of PR #506, but this is for `develop` branch.
See that PR for details.
> Updated configuration of special PMT readout channels

- fcl/gen/mevprtl/higgs/dissH_corsikap_kdif_M050.fcl
- fcl/gen/mevprtl/higgs/dissH_corsikap_kdif_M100.fcl
- fcl/gen/mevprtl/higgs/dissH_corsikap_kdif_M150.fcl
- fcl/gen/mevprtl/higgs/dissH_corsikap_kdif_M200.fcl
same as PR#500, but duplicated for production branch.
> add kdif-only fcls for higgs portal generator

- fcl/caf/cafmaker_defs.fcl
- fcl/reco/Definitions/stage1_icarus_defs.fcl
- icaruscode/Decode/fcl/deprecated/stage1_icarus_defs.fcl
duplicate pull request for new reconstruction flow feature branch
> added lines to run reconstruction for every PFO

- fcl/configurations/beamgates_icarus.fcl
- fcl/gen/MultiVertex/multivertex_icarus.fcl
- fcl/gen/background/prodbackground_Ar39_icarus.fcl
- fcl/gen/corsika/prodcorsika_proton_intime_icarus_bnb.fcl
- fcl/gen/corsika/prodcorsika_proton_intime_icarus_numi.fcl
- fcl/gen/corsika/prodcorsika_standard_icarus.fcl
- fcl/gen/genie/prodcorsika_genie_standard_icarus.fcl
- fcl/gen/genie/simulation_genie_icarus_bnb.fcl
- fcl/gen/genie/simulation_genie_icarus_simple.fcl
- fcl/gen/mevprtl/higgs/dissonant_higgs_gen.fcl
- fcl/gen/mevprtl/hnl/hnl_icarus_gen.fcl
- fcl/gen/numi/simulation_genie_icarus_numi.fcl
- fcl/gen/numi/simulation_numi.fcl
- fcl/gen/numi/simulation_numi_nue.fcl
- fcl/gen/numi/simulation_numi_numu.fcl
- fcl/gen/overlay/prodoverlay_proton_sbnflux_icarus.fcl
- fcl/gen/single/prodsingle_common_icarus.fcl
- fcl/gen/text/prodtext_standard_icarus.fcl
- fcl/reco/Definitions/stage0_icarus_mc_defs.fcl
- icaruscode/PMT/Trigger/simulate_triggers_icarus.fcl
- icaruscode/PMT/Trigger/trigger_emulation_icarus.fcl
- icaruscode/PMT/Trigger/trigger_icarus.fcl
This is the twin of PR #491, but to the production branch.
It is using the very same branch.
> Trigger simulation in production workflow [SBN2022B]

- fcl/reco/Definitions/stage0_icarus_defs.fcl
- fcl/reco/Definitions/stage0_icarus_mc_defs.fcl
- icaruscode/PMT/OpReco/fcl/icarus_ophitfinder.fcl
- icaruscode/PMT/extractpmtchannelbaseline_icarus.fcl
This is the twin PR of #526, but for the release branch SBN2022B.
This is actually the important one, since it's the one processing the new data.
> PMT baseline estimation added to Stage0 [SBN2022B]

- icaruscode/Decode/DecoderTools/TriggerDecoderV2_tool.cc
- icaruscode/Decode/DecoderTools/TriggerDecoderV3_tool.cc
This is the twin request of #531 for production branch.
General discussion should go into that PR.
This PR is provided with the sole purpose of keeping `develop` and production synchronised.
> Renamed trigger decoder tool classes [SBN2022B]

- fcl/reco/Stage1/Run2/stage1_run2_icarus_MC.fcl
- fcl/reco/Stage1/Run2/stage1_run2_nofilter_icarus.fcl
Issues that have been reported include the flash matching having been commented out for stage 1 running and that the default MC stage1 processing was requesting timing offsets. 
If others will add them here...
> Fixing fhicl file reported issues

- fcl/caf/cafmaker_defs.fcl
- fcl/caf/cafmakerjob_icarus_data.fcl
- icaruscode/PMT/Trigger/trigger_emulation_icarus.fcl
This is the twin PR of #557.
Discussion goes there.
As for review, I think as soon as that is approved, this should as well.
Anyway, I set as reviewers @SFBayLaser and @rennney in case they know about differences between production and development branch that warrant a specific change for this PR.
> Adding trigger emulation to CAF

- fcl/reco/Definitions/stage0_icarus_defs.fcl
- icaruscode/Filters/CMakeLists.txt
- icaruscode/Filters/FilterCRTPMTMatching_module.cc
- icaruscode/Filters/icarus_FilterCRTPMTMatching.fcl
This PR modifies the CRTPMTFiltering to use the DataProduct created by Anna instead of rerunning an analysis.
> Crtpmt filter with data product

- fcl/gen/numi/genie_icarus_numioffaxis.fcl
- fcl/gen/numi/prodcorsika_genie_protononly_icarus_numi_RHC.fcl
- fcl/gen/numi/simulation_genie_icarus_numi_RHC.fcl
Copy of https://github.com/SBNSoftware/icaruscode/pull/573, intended for develop branch.
> Add in simulation configs with RHC NuMI flux configuration

- fcl/reco/CMakeLists.txt
- fcl/reco/ntuple/CMakeLists.txt
- fcl/reco/ntuple/calibntupler_icarus.fcl
Copy of https://github.com/SBNSoftware/icaruscode/pull/574, intended for develop.
> Add in standalone Calibration NTupler configs

- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
Twin PR of #597.
All grief goes there.
> Fix to PMT decoder bug [SBN2023A]

- icaruscode/CRT/CRTPMTMatchingAna_module.cc
This was already addressed in Develop, and needed tobe propagated in Production.
> This fixes a bug in clearing vectors.

- fcl/gen/genie/prodcorsika_overlay_protononly_icarus.fcl
New fcl file for the generation of cosmic overlay with neutrino interactions as input in ICARUS
> New fcl for cosmic overlay

- icaruscode/Analysis/trigger/TimeTrackTreeStorageCRT_module.cc
This is a technical change: the module used to extract information from Stage1 _art_/ROOT files into a custom analysis tree uses chained associations to get the time of a track. It used to do the traversal in-house, now it uses the utility introduced in SBNSoftware/icarusalg#69.
Tested that it gives the same results as before.
Reviewers... @jzettle because he used and coauthored the module.
Note: it might conflict with #602 — in that case, merge that one first and then knock at my door.
> Trigger efficiency tree: adopted association traversal utility

- icaruscode/Utilities/ArtHandleTrackerManager.h
This is a twin of #615, but for the production branch. Review goes there.
> ArtHandleTrackerManager can now handle invalid handles [SBN2023A]

- fcl/reco/Definitions/CAEN_V1730_setup_icarus.fcl
- fcl/utilities/dump_hits_icarus.fcl
- fcl/utilities/dump_ophits_icarus.fcl
- icaruscode/Decode/ChannelMapping/ChannelMapPostGres_tool.cc
- icaruscode/Decode/ChannelMapping/ChannelMapSQLite_tool.cc
- icaruscode/Decode/ChannelMapping/ICARUSChannelMapProvider.cxx
- icaruscode/Decode/ChannelMapping/ICARUSChannelMapProvider.h
- icaruscode/Decode/ChannelMapping/ICARUSChannelMap_service.cc
- icaruscode/Decode/ChannelMapping/IChannelMapping.h
- icaruscode/Decode/ChannelMapping/IICARUSChannelMap.h
- icaruscode/Decode/ChannelMapping/PMTChannelMapDumper.cxx
- icaruscode/Decode/ChannelMapping/RunPeriods.h
- icaruscode/Timing/PMTWaveformTimeCorrectionExtractor.cxx
- icaruscode/Timing/PMTWaveformTimeCorrectionExtractor.h
This is the production version (i.e. the important version) of PR #620.
They contain the very same commits. :cherries: 
It is imperative that this goes into release as quick as possible once it's ready ~(and now it is _NOT_ ready yet)~ so that production can keep up.
The cable swapping which this request reflects is expected to happen momentarily (in the coming hours), after which we can update the hard-coded run number boundary of the change, and when _that_ commit is also in, dris PR is ready to go.
~Until then, it's draft.~
> Run-period-dependent channel mapping [SBN2023A]

- CMakeLists.txt
- icaruscode/Analysis/ICARUSPurityDQM_module.cc
- icaruscode/Analysis/ThroughgoingmuonAnalyzer_module.cc
- icaruscode/Analysis/trigger/TimeTrackTreeStorage_module.cc
- icaruscode/CRT/CRTPMTMatchingAna_module.cc
- icaruscode/CRT/CRTUtils/CRTHitRecoAlg.cc
- icaruscode/Decode/ChannelMapping/PMTChannelMapDumper.cxx
- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
- icaruscode/Decode/DecoderTools/TPCNoiseFilter1D_tool.cc
- icaruscode/Decode/DecoderTools/details/KeyValuesData.h
- icaruscode/IcarusObj/OpDetWaveformMeta.h
- icaruscode/PMT/Algorithms/NoiseGeneratorAlg.h
- icaruscode/PMT/Algorithms/PedestalGeneratorAlg.h
- icaruscode/PMT/Calibration/PMTBackgroundphotonsCalibration_module.cc
- icaruscode/PMT/OpReco/ICARUSMCOpFlash_module.cc
- icaruscode/PMT/PhotonPropogationICARUS_module.cc
- icaruscode/PMT/Trigger/Algorithms/ManagedTriggerGateBuilder.tcc
- icaruscode/PMT/Trigger/Algorithms/SlidingWindowDefs.h
- icaruscode/PMT/Trigger/Algorithms/WindowChannelMap.h
- icaruscode/PMT/Trigger/LVDSgates_module.cc
- icaruscode/PMT/Trigger/SlidingWindowTrigger_module.cc
- icaruscode/PMT/Trigger/TriggerEfficiencyPlots_module.cc
- icaruscode/TPC/SignalProcessing/HitFinder/ICARUSHitFinder_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/RecoWireICARUSRaw_module.cc
- icaruscode/TPC/Tracking/cluster3D/Cluster3DICARUS_module.cc
- icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
- icaruscode/Utilities/ArtHandleTrackerManager.h
- ups/product_deps
Updates provided by Lynn Garren to build with the new compilers now used for LArSoft
> Updates for e26 and c14 qualifiers

- fcl/caf/cafmaker_add_detsim2d_icarus.fcl
- fcl/caf/cafmaker_defs.fcl
- fcl/caf/cafmakerjob_icarus_data.fcl
- icaruscode/TPC/Calorimetry/NormalizeTPCSQL_tool.cc
- icaruscode/TPC/Calorimetry/NormalizeTPC_tool.cc
- icaruscode/TPC/Calorimetry/NormalizeYZSQL_tool.cc
- icaruscode/TPC/Calorimetry/NormalizeYZ_tool.cc
- icaruscode/TPC/Calorimetry/calorimetryICARUS.fcl
- icaruscode/TPC/Calorimetry/icarus_data_recombination.fcl
- icaruscode/TPC/Calorimetry/normtools_icarus.fcl
- icaruscode/TPC/ICARUSWireCell/detsimmodules_wirecell_ICARUS.fcl
Updates calibration factors and implements EMB recombination.
> Update to Energy Scale Calibration

- fcl/configurations/flashmatch_simple_icarus.fcl
> Patch for SimpleFlash

- fcl/detsim/detsim_2d_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_icarus.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_icarus_keepup.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_icarus_mc.fcl
- fcl/reco/Stage0/Run2/stage0_run2_wc_raw_icarus_mc.fcl
- fcl/reco/Stage1/Run2/stage1_run2_wc_icarus_MC.fcl
- icaruscode/Decode/DecoderTools/decoderTools_icarus.fcl
Basically setting fhicl parameters to utilize latest improvemens
Also introduce a "keepup" stage 0 file to run the purity analysis for keep up jobs
> Stage0 and Stage1 fhicl file updates for 2D deconvlution improvements

- icaruscode/PMT/Trigger/DiscriminatedAdderSignal_module.cc
> DiscriminatedAdderSignal: fixed two assertions

- icaruscode/PMT/Trigger/DiscriminatedAdderSignal_module.cc
> DiscriminatedAdderSignal: fix another assertion

- icaruscode/Analysis/ICARUSPurityDQM_module.cc
The correction introduced should remove the failures in stage0 due to the purity analysis
> Updates on the purity module that is used at stage0

- icaruscode/Utilities/ReadArtConfiguration.h
The bug is discussed in issue #14 of art-framework-suite/fhicl-cpp (https://github.com/art-framework-suite/fhicl-cpp/issues/14). The workaround is that `util::readConfigurationFromArtPrincipal` t emits a warning if an expected configuration is not present, instead of throwing an exception. That puts the load on the caller for checking that the configuration that is needed is actually present (in some of the cases we have seen, it was, so no harm done).
This workaround will cover only the trigger and PMT configuration extraction.
Lookup of the configuration is also performed in some standard LArSoft services (`DetectorClocks` and `DetectorProperties`), where no issue has been reported, and in `CAFMaker` of SBNSoftware/sbncode, that this workaround does not cover.
It _is_ possible to port …
> Workaround on FHiCL parameter set bug

- fcl/g4/larg4_icarus.fcl
- fcl/g4/simplemerge_icarus.fcl
merging "largeant" and "largeant:droppedMCParticles" for ML reco
> add simplemerge

- fcl/gen/numi/genie_icarus_numioffaxis.fcl
Clone of #747 specifically for 2024A
> update paths to point to the latest numi flux production

- icaruscode/TPC/Calorimetry/calorimetryICARUS.fcl
Add in missing prameters to the gnocchi fcl block
> Add default fcl params to gnocchi table

- icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
This PR cleans up the PMT decoder by removing an unused and confusing option for correcting the cable delays in the propagation of the PPS signals that reset the TTT counters. This option is a leftover of an old implementation in which the delays were supposed to be read from board-by-board `TTTResetDelay` values in `CAEN_V1730_setup_icarus.fcl`. 
The reasons for its removal are several:
1. This archaic option was never finalized or used.
2. The TTT reset delay corrections are now handled in a much better way via a calibration database. 
3. It's confusing to have two places in the code where the TTT reset delays can be inserted.
The proposed changes completely remove any reference to `TTTResetDelay` from the decoder. In addition, some of the documention is updated to better reflect the …
> Remove unused TTTResetDelay, improve documentation

- icaruscode/Analysis/TPCPurityMonitor_module.cc
- icaruscode/Analysis/ThroughgoingmuonAnalyzer_module.cc
- icaruscode/Analysis/tools/BasicHitAnalysis_tool.cc
- icaruscode/Analysis/tools/HitEfficiencyAnalysis_tool.cc
- icaruscode/Analysis/tools/HitFinderAnalysis_tool.cc
- icaruscode/Analysis/tools/SpacePointAnalysisMC_tool.cc
- icaruscode/Analysis/tools/SpacePointAnalysis_tool.cc
- icaruscode/Analysis/tools/TrackHitEfficiencyAnalysis_tool.cc
- icaruscode/Analysis/trigger/TimeTrackTreeStorageCRT_module.cc
- icaruscode/Analysis/trigger/TimeTrackTreeStorage_module.cc
- icaruscode/TPC/SignalProcessing/HitFinder/HitConverter_module.cc
- icaruscode/TPC/SignalProcessing/RecoWire/SimTestPulse/SimTestPulseAna_module.cc
Pursuant to changes introduced in https://github.com/LArSoft/lardataobj/pull/42.
> Accommodate changes to recob::Hit

- fcl/gen/numi/genie_icarus_numioffaxis.fcl
I updated the search paths for Genie to locate the flux files, from version v03_00 to v03_02, redirecting them to the most recent set.
> Updating NUMI flux files v3_00 --> v3_02

- fcl/gen/numi/genie_icarus_numioffaxis.fcl
I updated Genie's search paths to point to the latest set of flux files, changing from version v03_01 to v03_02.
> Updating NUMI flux files v3_01 --> v3_02 [release/SBN2024A]

- ups/product_deps
Just a test PR to run the CI test
> Updating dependencies
